package com.healthcare.labtestbooking.entity.enums;

public enum OrderStatus {
    PENDING,
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    TECHNICIAN_ASSIGNED,
    SAMPLE_COLLECTED,
    SAMPLE_RECEIVED_AT_LAB,
    PROCESSING,
    REPORT_GENERATED,
    REPORT_READY,
    DELIVERED,
    CANCELLATION_REQUESTED,
    CANCELLATION_CONFIRMED,
    REFUND_PROCESSED
}
