INSERT INTO tests (name, slug, category, description, short_description, price, original_price, sample_type, fasting_required, turnaround_time, is_active)
VALUES
('Complete Blood Count (CBC)', 'complete-blood-count-cbc-1', 'Hematology', 'Comprehensive Complete Blood Count (CBC) test.', 'Complete Blood Count (CBC) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Hemoglobin (Hb)', 'hemoglobin-hb-2', 'Hematology', 'Comprehensive Hemoglobin (Hb) test.', 'Hemoglobin (Hb) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Total Leukocyte Count (TLC)', 'total-leukocyte-count-tlc-3', 'Hematology', 'Comprehensive Total Leukocyte Count (TLC) test.', 'Total Leukocyte Count (TLC) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Differential Leukocyte Count (DLC)', 'differential-leukocyte-count-dlc-4', 'Hematology', 'Comprehensive Differential Leukocyte Count (DLC) test.', 'Differential Leukocyte Count (DLC) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Platelet Count', 'platelet-count-5', 'Hematology', 'Comprehensive Platelet Count test.', 'Platelet Count analysis.', 99, 129, 'Blood', 0, '1hr', true),
('RBC Count', 'rbc-count-6', 'Hematology', 'Comprehensive RBC Count test.', 'RBC Count analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Hematocrit (PCV)', 'hematocrit-pcv-7', 'Hematology', 'Comprehensive Hematocrit (PCV) test.', 'Hematocrit (PCV) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('MCV, MCH, MCHC (RBC Indices)', 'mcv-mch-mchc-rbc-indices-8', 'Hematology', 'Comprehensive MCV, MCH, MCHC (RBC Indices) test.', 'MCV, MCH, MCHC (RBC Indices) analysis.', 149, 194, 'Blood', 0, '2hr', true),
('RDW (Red Cell Distribution Width)', 'rdw-red-cell-distribution-width-9', 'Hematology', 'Comprehensive RDW (Red Cell Distribution Width) test.', 'RDW (Red Cell Distribution Width) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('MPV (Mean Platelet Volume)', 'mpv-mean-platelet-volume-10', 'Hematology', 'Comprehensive MPV (Mean Platelet Volume) test.', 'MPV (Mean Platelet Volume) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('ESR (Erythrocyte Sedimentation Rate)', 'esr-erythrocyte-sedimentation-rate-11', 'Hematology', 'Comprehensive ESR (Erythrocyte Sedimentation Rate) test.', 'ESR (Erythrocyte Sedimentation Rate) analysis.', 149, 194, 'Blood', 0, '2hr', true),
('Reticulocyte Count', 'reticulocyte-count-12', 'Hematology', 'Comprehensive Reticulocyte Count test.', 'Reticulocyte Count analysis.', 149, 194, 'Blood', 0, '4hr', true),
('Absolute Eosinophil Count (AEC)', 'absolute-eosinophil-count-aec-13', 'Hematology', 'Comprehensive Absolute Eosinophil Count (AEC) test.', 'Absolute Eosinophil Count (AEC) analysis.', 129, 168, 'Blood', 0, '2hr', true),
('Peripheral Blood Smear (PBS)', 'peripheral-blood-smear-pbs-14', 'Hematology', 'Comprehensive Peripheral Blood Smear (PBS) test.', 'Peripheral Blood Smear (PBS) analysis.', 149, 194, 'Blood', 0, '4hr', true),
('Bone Marrow Examination', 'bone-marrow-examination-15', 'Hematology', 'Comprehensive Bone Marrow Examination test.', 'Bone Marrow Examination analysis.', 2500, 3250, 'Blood', 0, '72hr', true),
('Coombs Test (Direct)', 'coombs-test-direct-16', 'Hematology', 'Comprehensive Coombs Test (Direct) test.', 'Coombs Test (Direct) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Coombs Test (Indirect)', 'coombs-test-indirect-17', 'Hematology', 'Comprehensive Coombs Test (Indirect) test.', 'Coombs Test (Indirect) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Cold Agglutinins', 'cold-agglutinins-18', 'Hematology', 'Comprehensive Cold Agglutinins test.', 'Cold Agglutinins analysis.', 249, 324, 'Blood', 0, '24hr', true),
('Cryoglobulins', 'cryoglobulins-19', 'Hematology', 'Comprehensive Cryoglobulins test.', 'Cryoglobulins analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Hemoglobin Electrophoresis', 'hemoglobin-electrophoresis-20', 'Hematology', 'Comprehensive Hemoglobin Electrophoresis test.', 'Hemoglobin Electrophoresis analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Sickle Cell Test', 'sickle-cell-test-21', 'Hematology', 'Comprehensive Sickle Cell Test test.', 'Sickle Cell Test analysis.', 199, 259, 'Blood', 0, '4hr', true),
('G6PD Deficiency Test', 'g6pd-deficiency-test-22', 'Hematology', 'Comprehensive G6PD Deficiency Test test.', 'G6PD Deficiency Test analysis.', 249, 324, 'Blood', 0, '24hr', true),
('Thalassemia Screening', 'thalassemia-screening-23', 'Hematology', 'Comprehensive Thalassemia Screening test.', 'Thalassemia Screening analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Plasma Hemoglobin', 'plasma-hemoglobin-24', 'Hematology', 'Comprehensive Plasma Hemoglobin test.', 'Plasma Hemoglobin analysis.', 199, 259, 'Blood', 0, '4hr', true),
('Haptoglobin', 'haptoglobin-25', 'Hematology', 'Comprehensive Haptoglobin test.', 'Haptoglobin analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Prothrombin Time (PT/INR)', 'prothrombin-time-pt-inr-26', 'Coagulation', 'Comprehensive Prothrombin Time (PT/INR) test.', 'Prothrombin Time (PT/INR) analysis.', 279, 363, 'Blood', 0, '24hr', true),
('Activated Partial Thromboplastin Time (APTT)', 'activated-partial-thromboplastin-time-aptt-27', 'Coagulation', 'Comprehensive Activated Partial Thromboplastin Time (APTT) test.', 'Activated Partial Thromboplastin Time (APTT) analysis.', 249, 324, 'Blood', 0, '24hr', true),
('Thrombin Time (TT)', 'thrombin-time-tt-28', 'Coagulation', 'Comprehensive Thrombin Time (TT) test.', 'Thrombin Time (TT) analysis.', 199, 259, 'Blood', 0, '24hr', true),
('Bleeding Time (BT)', 'bleeding-time-bt-29', 'Coagulation', 'Comprehensive Bleeding Time (BT) test.', 'Bleeding Time (BT) analysis.', 99, 129, 'Blood', 0, '1hr', true),
('Clotting Time (CT)', 'clotting-time-ct-30', 'Coagulation', 'Comprehensive Clotting Time (CT) test.', 'Clotting Time (CT) analysis.', 99, 129, 'Blood', 0, '1hr', true),
('D-Dimer', 'd-dimer-31', 'Coagulation', 'Comprehensive D-Dimer test.', 'D-Dimer analysis.', 399, 519, 'Blood', 0, '24hr', true),
('Fibrinogen Level', 'fibrinogen-level-32', 'Coagulation', 'Comprehensive Fibrinogen Level test.', 'Fibrinogen Level analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Factor VIII Assay', 'factor-viii-assay-33', 'Coagulation', 'Comprehensive Factor VIII Assay test.', 'Factor VIII Assay analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('Factor IX Assay', 'factor-ix-assay-34', 'Coagulation', 'Comprehensive Factor IX Assay test.', 'Factor IX Assay analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('von Willebrand Factor (vWF)', 'von-willebrand-factor-vwf-35', 'Coagulation', 'Comprehensive von Willebrand Factor (vWF) test.', 'von Willebrand Factor (vWF) analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('Protein C', 'protein-c-36', 'Coagulation', 'Comprehensive Protein C test.', 'Protein C analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Protein S', 'protein-s-37', 'Coagulation', 'Comprehensive Protein S test.', 'Protein S analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Antithrombin III', 'antithrombin-iii-38', 'Coagulation', 'Comprehensive Antithrombin III test.', 'Antithrombin III analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Lupus Anticoagulant', 'lupus-anticoagulant-39', 'Coagulation', 'Comprehensive Lupus Anticoagulant test.', 'Lupus Anticoagulant analysis.', 799, 1039, 'Blood', 0, '72hr', true),
('Mixing Study', 'mixing-study-40', 'Coagulation', 'Comprehensive Mixing Study test.', 'Mixing Study analysis.', 699, 909, 'Blood', 0, '48hr', true),
('Lipid Profile (Complete)', 'lipid-profile-complete-41', 'Cardiac & Lipid', 'Comprehensive Lipid Profile (Complete) test.', 'Lipid Profile (Complete) analysis.', 399, 519, 'Blood', 1, '24hr', true),
('Total Cholesterol', 'total-cholesterol-42', 'Cardiac & Lipid', 'Comprehensive Total Cholesterol test.', 'Total Cholesterol analysis.', 149, 194, 'Blood', 1, '24hr', true),
('HDL Cholesterol', 'hdl-cholesterol-43', 'Cardiac & Lipid', 'Comprehensive HDL Cholesterol test.', 'HDL Cholesterol analysis.', 149, 194, 'Blood', 1, '24hr', true),
('LDL Cholesterol', 'ldl-cholesterol-44', 'Cardiac & Lipid', 'Comprehensive LDL Cholesterol test.', 'LDL Cholesterol analysis.', 149, 194, 'Blood', 1, '24hr', true),
('VLDL Cholesterol', 'vldl-cholesterol-45', 'Cardiac & Lipid', 'Comprehensive VLDL Cholesterol test.', 'VLDL Cholesterol analysis.', 149, 194, 'Blood', 1, '24hr', true),
('Triglycerides', 'triglycerides-46', 'Cardiac & Lipid', 'Comprehensive Triglycerides test.', 'Triglycerides analysis.', 149, 194, 'Blood', 1, '24hr', true),
('Non-HDL Cholesterol', 'non-hdl-cholesterol-47', 'Cardiac & Lipid', 'Comprehensive Non-HDL Cholesterol test.', 'Non-HDL Cholesterol analysis.', 199, 259, 'Blood', 1, '24hr', true),
('Lipoprotein (a)', 'lipoprotein-a-48', 'Cardiac & Lipid', 'Comprehensive Lipoprotein (a) test.', 'Lipoprotein (a) analysis.', 499, 649, 'Blood', 1, '48hr', true),
('Apolipoprotein A1', 'apolipoprotein-a1-49', 'Cardiac & Lipid', 'Comprehensive Apolipoprotein A1 test.', 'Apolipoprotein A1 analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Apolipoprotein B', 'apolipoprotein-b-50', 'Cardiac & Lipid', 'Comprehensive Apolipoprotein B test.', 'Apolipoprotein B analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Apo B/Apo A1 Ratio', 'apo-b-apo-a1-ratio-51', 'Cardiac & Lipid', 'Comprehensive Apo B/Apo A1 Ratio test.', 'Apo B/Apo A1 Ratio analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Troponin I', 'troponin-i-52', 'Cardiac & Lipid', 'Comprehensive Troponin I test.', 'Troponin I analysis.', 599, 779, 'Blood', 0, '4hr', true),
('Troponin T', 'troponin-t-53', 'Cardiac & Lipid', 'Comprehensive Troponin T test.', 'Troponin T analysis.', 599, 779, 'Blood', 0, '4hr', true),
('CK-MB', 'ck-mb-54', 'Cardiac & Lipid', 'Comprehensive CK-MB test.', 'CK-MB analysis.', 399, 519, 'Blood', 0, '4hr', true),
('Creatine Kinase (CK)', 'creatine-kinase-ck-55', 'Cardiac & Lipid', 'Comprehensive Creatine Kinase (CK) test.', 'Creatine Kinase (CK) analysis.', 249, 324, 'Blood', 0, '4hr', true),
('Lactate Dehydrogenase (LDH)', 'lactate-dehydrogenase-ldh-56', 'Cardiac & Lipid', 'Comprehensive Lactate Dehydrogenase (LDH) test.', 'Lactate Dehydrogenase (LDH) analysis.', 149, 194, 'Blood', 0, '2hr', true),
('Myoglobin', 'myoglobin-57', 'Cardiac & Lipid', 'Comprehensive Myoglobin test.', 'Myoglobin analysis.', 399, 519, 'Blood', 0, '4hr', true),
('Homocysteine', 'homocysteine-58', 'Cardiac & Lipid', 'Comprehensive Homocysteine test.', 'Homocysteine analysis.', 599, 779, 'Blood', 1, '48hr', true),
('hs-CRP (Cardiac Risk)', 'hs-crp-cardiac-risk-59', 'Cardiac & Lipid', 'Comprehensive hs-CRP (Cardiac Risk) test.', 'hs-CRP (Cardiac Risk) analysis.', 399, 519, 'Blood', 0, '24hr', true),
('NT-proBNP', 'nt-probnp-60', 'Cardiac & Lipid', 'Comprehensive NT-proBNP test.', 'NT-proBNP analysis.', 899, 1169, 'Blood', 0, '24hr', true),
('Liver Function Test (LFT) Complete', 'liver-function-test-lft-complete-61', 'Liver Function', 'Comprehensive Liver Function Test (LFT) Complete test.', 'Liver Function Test (LFT) Complete analysis.', 349, 454, 'Blood', 0, '24hr', true),
('ALT (SGPT)', 'alt-sgpt-62', 'Liver Function', 'Comprehensive ALT (SGPT) test.', 'ALT (SGPT) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('AST (SGOT)', 'ast-sgot-63', 'Liver Function', 'Comprehensive AST (SGOT) test.', 'AST (SGOT) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('ALP (Alkaline Phosphatase)', 'alp-alkaline-phosphatase-64', 'Liver Function', 'Comprehensive ALP (Alkaline Phosphatase) test.', 'ALP (Alkaline Phosphatase) analysis.', 129, 168, 'Blood', 0, '2hr', true),
('GGT (Gamma GT)', 'ggt-gamma-gt-65', 'Liver Function', 'Comprehensive GGT (Gamma GT) test.', 'GGT (Gamma GT) analysis.', 149, 194, 'Blood', 0, '2hr', true),
('Total Bilirubin', 'total-bilirubin-66', 'Liver Function', 'Comprehensive Total Bilirubin test.', 'Total Bilirubin analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Direct Bilirubin', 'direct-bilirubin-67', 'Liver Function', 'Comprehensive Direct Bilirubin test.', 'Direct Bilirubin analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Indirect Bilirubin', 'indirect-bilirubin-68', 'Liver Function', 'Comprehensive Indirect Bilirubin test.', 'Indirect Bilirubin analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Total Protein', 'total-protein-69', 'Liver Function', 'Comprehensive Total Protein test.', 'Total Protein analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Serum Albumin', 'serum-albumin-70', 'Liver Function', 'Comprehensive Serum Albumin test.', 'Serum Albumin analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Serum Globulin', 'serum-globulin-71', 'Liver Function', 'Comprehensive Serum Globulin test.', 'Serum Globulin analysis.', 99, 129, 'Blood', 0, '2hr', true),
('A/G Ratio', 'a-g-ratio-72', 'Liver Function', 'Comprehensive A/G Ratio test.', 'A/G Ratio analysis.', 129, 168, 'Blood', 0, '2hr', true),
('LDH (Liver Isoenzyme)', 'ldh-liver-isoenzyme-73', 'Liver Function', 'Comprehensive LDH (Liver Isoenzyme) test.', 'LDH (Liver Isoenzyme) analysis.', 249, 324, 'Blood', 0, '24hr', true),
('5'' Nucleotidase', '5-nucleotidase-74', 'Liver Function', 'Comprehensive 5'' Nucleotidase test.', '5'' Nucleotidase analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Cholinesterase', 'cholinesterase-75', 'Liver Function', 'Comprehensive Cholinesterase test.', 'Cholinesterase analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Ammonia', 'ammonia-76', 'Liver Function', 'Comprehensive Ammonia test.', 'Ammonia analysis.', 399, 519, 'Blood', 0, '2hr', true),
('Ceruloplasmin', 'ceruloplasmin-77', 'Liver Function', 'Comprehensive Ceruloplasmin test.', 'Ceruloplasmin analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Alpha-1 Antitrypsin', 'alpha-1-antitrypsin-78', 'Liver Function', 'Comprehensive Alpha-1 Antitrypsin test.', 'Alpha-1 Antitrypsin analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Ferritin', 'ferritin-79', 'Liver Function', 'Comprehensive Ferritin test.', 'Ferritin analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Iron (Serum)', 'iron-serum-80', 'Liver Function', 'Comprehensive Iron (Serum) test.', 'Iron (Serum) analysis.', 149, 194, 'Blood', 1, '2hr', true),
('TIBC', 'tibc-81', 'Liver Function', 'Comprehensive TIBC test.', 'TIBC analysis.', 199, 259, 'Blood', 1, '24hr', true),
('UIBC', 'uibc-82', 'Liver Function', 'Comprehensive UIBC test.', 'UIBC analysis.', 199, 259, 'Blood', 1, '24hr', true),
('Transferrin', 'transferrin-83', 'Liver Function', 'Comprehensive Transferrin test.', 'Transferrin analysis.', 249, 324, 'Blood', 1, '24hr', true),
('Transferrin Saturation', 'transferrin-saturation-84', 'Liver Function', 'Comprehensive Transferrin Saturation test.', 'Transferrin Saturation analysis.', 299, 389, 'Blood', 1, '24hr', true),
('Copper', 'copper-85', 'Liver Function', 'Comprehensive Copper test.', 'Copper analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Kidney Function Test (RFT) Complete', 'kidney-function-test-rft-complete-86', 'Kidney Function', 'Comprehensive Kidney Function Test (RFT) Complete test.', 'Kidney Function Test (RFT) Complete analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Blood Urea Nitrogen (BUN)', 'blood-urea-nitrogen-bun-87', 'Kidney Function', 'Comprehensive Blood Urea Nitrogen (BUN) test.', 'Blood Urea Nitrogen (BUN) analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Serum Creatinine', 'serum-creatinine-88', 'Kidney Function', 'Comprehensive Serum Creatinine test.', 'Serum Creatinine analysis.', 99, 129, 'Blood', 0, '2hr', true),
('Uric Acid', 'uric-acid-89', 'Kidney Function', 'Comprehensive Uric Acid test.', 'Uric Acid analysis.', 129, 168, 'Blood', 0, '2hr', true),
('BUN/Creatinine Ratio', 'bun-creatinine-ratio-90', 'Kidney Function', 'Comprehensive BUN/Creatinine Ratio test.', 'BUN/Creatinine Ratio analysis.', 149, 194, 'Blood', 0, '2hr', true),
('eGFR', 'egfr-91', 'Kidney Function', 'Comprehensive eGFR test.', 'eGFR analysis.', 149, 194, 'Blood', 0, '24hr', true),
('Cystatin C', 'cystatin-c-92', 'Kidney Function', 'Comprehensive Cystatin C test.', 'Cystatin C analysis.', 449, 584, 'Blood', 0, '24hr', true),
('Microalbumin (Urine)', 'microalbumin-urine-93', 'Kidney Function', 'Comprehensive Microalbumin (Urine) test.', 'Microalbumin (Urine) analysis.', 199, 259, 'Blood', 0, '24hr', true),
('Albumin/Creatinine Ratio (ACR)', 'albumin-creatinine-ratio-acr-94', 'Kidney Function', 'Comprehensive Albumin/Creatinine Ratio (ACR) test.', 'Albumin/Creatinine Ratio (ACR) analysis.', 249, 324, 'Blood', 0, '24hr', true),
('Protein/Creatinine Ratio (PCR)', 'protein-creatinine-ratio-pcr-95', 'Kidney Function', 'Comprehensive Protein/Creatinine Ratio (PCR) test.', 'Protein/Creatinine Ratio (PCR) analysis.', 249, 324, 'Blood', 0, '24hr', true),
('24-Hour Urine Protein', '24-hour-urine-protein-96', 'Kidney Function', 'Comprehensive 24-Hour Urine Protein test.', '24-Hour Urine Protein analysis.', 299, 389, 'Blood', 0, '48hr', true),
('24-Hour Urine Creatinine', '24-hour-urine-creatinine-97', 'Kidney Function', 'Comprehensive 24-Hour Urine Creatinine test.', '24-Hour Urine Creatinine analysis.', 199, 259, 'Blood', 0, '48hr', true),
('24-Hour Urine Urea', '24-hour-urine-urea-98', 'Kidney Function', 'Comprehensive 24-Hour Urine Urea test.', '24-Hour Urine Urea analysis.', 199, 259, 'Blood', 0, '48hr', true),
('24-Hour Urine Uric Acid', '24-hour-urine-uric-acid-99', 'Kidney Function', 'Comprehensive 24-Hour Urine Uric Acid test.', '24-Hour Urine Uric Acid analysis.', 199, 259, 'Blood', 0, '48hr', true),
('24-Hour Urine Calcium', '24-hour-urine-calcium-100', 'Kidney Function', 'Comprehensive 24-Hour Urine Calcium test.', '24-Hour Urine Calcium analysis.', 199, 259, 'Blood', 0, '48hr', true),
('24-Hour Urine Phosphorus', '24-hour-urine-phosphorus-101', 'Kidney Function', 'Comprehensive 24-Hour Urine Phosphorus test.', '24-Hour Urine Phosphorus analysis.', 199, 259, 'Blood', 0, '48hr', true),
('24-Hour Urine Sodium', '24-hour-urine-sodium-102', 'Kidney Function', 'Comprehensive 24-Hour Urine Sodium test.', '24-Hour Urine Sodium analysis.', 199, 259, 'Blood', 0, '48hr', true),
('24-Hour Urine Potassium', '24-hour-urine-potassium-103', 'Kidney Function', 'Comprehensive 24-Hour Urine Potassium test.', '24-Hour Urine Potassium analysis.', 199, 259, 'Blood', 0, '48hr', true),
('24-Hour Urine Chloride', '24-hour-urine-chloride-104', 'Kidney Function', 'Comprehensive 24-Hour Urine Chloride test.', '24-Hour Urine Chloride analysis.', 199, 259, 'Blood', 0, '48hr', true),
('24-Hour Urine Magnesium', '24-hour-urine-magnesium-105', 'Kidney Function', 'Comprehensive 24-Hour Urine Magnesium test.', '24-Hour Urine Magnesium analysis.', 249, 324, 'Blood', 0, '48hr', true),
('Fasting Blood Sugar (FBS)', 'fasting-blood-sugar-fbs-106', 'Diabetes', 'Comprehensive Fasting Blood Sugar (FBS) test.', 'Fasting Blood Sugar (FBS) analysis.', 149, 194, 'Blood', 1, '24hr', true),
('Postprandial Blood Sugar (PPBS)', 'postprandial-blood-sugar-ppbs-107', 'Diabetes', 'Comprehensive Postprandial Blood Sugar (PPBS) test.', 'Postprandial Blood Sugar (PPBS) analysis.', 149, 194, 'Blood', 0, '24hr', true),
('Random Blood Sugar (RBS)', 'random-blood-sugar-rbs-108', 'Diabetes', 'Comprehensive Random Blood Sugar (RBS) test.', 'Random Blood Sugar (RBS) analysis.', 149, 194, 'Blood', 0, '2hr', true),
('HbA1c (Glycated Hemoglobin)', 'hba1c-glycated-hemoglobin-109', 'Diabetes', 'Comprehensive HbA1c (Glycated Hemoglobin) test.', 'HbA1c (Glycated Hemoglobin) analysis.', 179, 233, 'Blood', 0, '24hr', true),
('Glucose Tolerance Test (GTT)', 'glucose-tolerance-test-gtt-110', 'Diabetes', 'Comprehensive Glucose Tolerance Test (GTT) test.', 'Glucose Tolerance Test (GTT) analysis.', 299, 389, 'Blood', 1, '4hr', true),
('Insulin (Fasting)', 'insulin-fasting-111', 'Diabetes', 'Comprehensive Insulin (Fasting) test.', 'Insulin (Fasting) analysis.', 399, 519, 'Blood', 1, '24hr', true),
('Insulin (Postprandial)', 'insulin-postprandial-112', 'Diabetes', 'Comprehensive Insulin (Postprandial) test.', 'Insulin (Postprandial) analysis.', 399, 519, 'Blood', 0, '24hr', true),
('C-Peptide', 'c-peptide-113', 'Diabetes', 'Comprehensive C-Peptide test.', 'C-Peptide analysis.', 449, 584, 'Blood', 1, '24hr', true),
('Proinsulin', 'proinsulin-114', 'Diabetes', 'Comprehensive Proinsulin test.', 'Proinsulin analysis.', 599, 779, 'Blood', 1, '48hr', true),
('HOMA-IR (Insulin Resistance)', 'homa-ir-insulin-resistance-115', 'Diabetes', 'Comprehensive HOMA-IR (Insulin Resistance) test.', 'HOMA-IR (Insulin Resistance) analysis.', 499, 649, 'Blood', 1, '24hr', true),
('Fructosamine', 'fructosamine-116', 'Diabetes', 'Comprehensive Fructosamine test.', 'Fructosamine analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Lactate', 'lactate-117', 'Diabetes', 'Comprehensive Lactate test.', 'Lactate analysis.', 299, 389, 'Blood', 0, '2hr', true),
('Pyruvate', 'pyruvate-118', 'Diabetes', 'Comprehensive Pyruvate test.', 'Pyruvate analysis.', 349, 454, 'Blood', 0, '2hr', true),
('Ketone Bodies (Blood)', 'ketone-bodies-blood-119', 'Diabetes', 'Comprehensive Ketone Bodies (Blood) test.', 'Ketone Bodies (Blood) analysis.', 199, 259, 'Blood', 0, '2hr', true),
('Beta-Hydroxybutyrate', 'beta-hydroxybutyrate-120', 'Diabetes', 'Comprehensive Beta-Hydroxybutyrate test.', 'Beta-Hydroxybutyrate analysis.', 249, 324, 'Blood', 0, '2hr', true),
('Thyroid Profile Total (T3,T4,TSH)', 'thyroid-profile-total-t3-t4-tsh-121', 'Thyroid', 'Comprehensive Thyroid Profile Total (T3,T4,TSH) test.', 'Thyroid Profile Total (T3,T4,TSH) analysis.', 449, 584, 'Blood', 0, '24hr', true),
('TSH (Ultra-sensitive)', 'tsh-ultra-sensitive-122', 'Thyroid', 'Comprehensive TSH (Ultra-sensitive) test.', 'TSH (Ultra-sensitive) analysis.', 199, 259, 'Blood', 0, '24hr', true),
('Free T3 (FT3)', 'free-t3-ft3-123', 'Thyroid', 'Comprehensive Free T3 (FT3) test.', 'Free T3 (FT3) analysis.', 249, 324, 'Blood', 0, '24hr', true),
('Free T4 (FT4)', 'free-t4-ft4-124', 'Thyroid', 'Comprehensive Free T4 (FT4) test.', 'Free T4 (FT4) analysis.', 249, 324, 'Blood', 0, '24hr', true),
('Total T3', 'total-t3-125', 'Thyroid', 'Comprehensive Total T3 test.', 'Total T3 analysis.', 199, 259, 'Blood', 0, '24hr', true),
('Total T4', 'total-t4-126', 'Thyroid', 'Comprehensive Total T4 test.', 'Total T4 analysis.', 199, 259, 'Blood', 0, '24hr', true),
('Reverse T3', 'reverse-t3-127', 'Thyroid', 'Comprehensive Reverse T3 test.', 'Reverse T3 analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Anti-TPO Antibodies', 'anti-tpo-antibodies-128', 'Thyroid', 'Comprehensive Anti-TPO Antibodies test.', 'Anti-TPO Antibodies analysis.', 349, 454, 'Blood', 0, '48hr', true),
('Anti-Tg Antibodies', 'anti-tg-antibodies-129', 'Thyroid', 'Comprehensive Anti-Tg Antibodies test.', 'Anti-Tg Antibodies analysis.', 349, 454, 'Blood', 0, '48hr', true),
('TSH Receptor Antibodies (TRAb)', 'tsh-receptor-antibodies-trab-130', 'Thyroid', 'Comprehensive TSH Receptor Antibodies (TRAb) test.', 'TSH Receptor Antibodies (TRAb) analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Thyroglobulin', 'thyroglobulin-131', 'Thyroid', 'Comprehensive Thyroglobulin test.', 'Thyroglobulin analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Calcitonin', 'calcitonin-132', 'Thyroid', 'Comprehensive Calcitonin test.', 'Calcitonin analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Electrolyte Panel (Na,K,Cl)', 'electrolyte-panel-na-k-cl-133', 'Electrolytes', 'Comprehensive Electrolyte Panel (Na,K,Cl) test.', 'Electrolyte Panel (Na,K,Cl) analysis.', 199, 259, 'Blood', 0, '1hr', true),
('Sodium (Na)', 'sodium-na-134', 'Electrolytes', 'Comprehensive Sodium (Na) test.', 'Sodium (Na) analysis.', 79, 103, 'Blood', 0, '1hr', true),
('Potassium (K)', 'potassium-k-135', 'Electrolytes', 'Comprehensive Potassium (K) test.', 'Potassium (K) analysis.', 79, 103, 'Blood', 0, '1hr', true),
('Chloride (Cl)', 'chloride-cl-136', 'Electrolytes', 'Comprehensive Chloride (Cl) test.', 'Chloride (Cl) analysis.', 79, 103, 'Blood', 0, '1hr', true),
('Bicarbonate (HCO3)', 'bicarbonate-hco3-137', 'Electrolytes', 'Comprehensive Bicarbonate (HCO3) test.', 'Bicarbonate (HCO3) analysis.', 99, 129, 'Blood', 0, '1hr', true),
('Anion Gap', 'anion-gap-138', 'Electrolytes', 'Comprehensive Anion Gap test.', 'Anion Gap analysis.', 129, 168, 'Blood', 0, '1hr', true),
('Calcium (Total)', 'calcium-total-139', 'Electrolytes', 'Comprehensive Calcium (Total) test.', 'Calcium (Total) analysis.', 129, 168, 'Blood', 0, '2hr', true),
('Calcium (Ionized)', 'calcium-ionized-140', 'Electrolytes', 'Comprehensive Calcium (Ionized) test.', 'Calcium (Ionized) analysis.', 199, 259, 'Blood', 0, '2hr', true),
('Phosphorus', 'phosphorus-141', 'Electrolytes', 'Comprehensive Phosphorus test.', 'Phosphorus analysis.', 129, 168, 'Blood', 0, '2hr', true),
('Magnesium', 'magnesium-142', 'Electrolytes', 'Comprehensive Magnesium test.', 'Magnesium analysis.', 179, 233, 'Blood', 0, '2hr', true),
('Iron', 'iron-143', 'Electrolytes', 'Comprehensive Iron test.', 'Iron analysis.', 149, 194, 'Blood', 1, '2hr', true),
('Zinc', 'zinc-144', 'Electrolytes', 'Comprehensive Zinc test.', 'Zinc analysis.', 299, 389, 'Blood', 0, '48hr', true),
('Copper', 'copper-145', 'Electrolytes', 'Comprehensive Copper test.', 'Copper analysis.', 299, 389, 'Blood', 0, '48hr', true),
('Selenium', 'selenium-146', 'Electrolytes', 'Comprehensive Selenium test.', 'Selenium analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Manganese', 'manganese-147', 'Electrolytes', 'Comprehensive Manganese test.', 'Manganese analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Chromium', 'chromium-148', 'Electrolytes', 'Comprehensive Chromium test.', 'Chromium analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Iodine', 'iodine-149', 'Electrolytes', 'Comprehensive Iodine test.', 'Iodine analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Fluoride', 'fluoride-150', 'Electrolytes', 'Comprehensive Fluoride test.', 'Fluoride analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Lead (Heavy Metal)', 'lead-heavy-metal-151', 'Electrolytes', 'Comprehensive Lead (Heavy Metal) test.', 'Lead (Heavy Metal) analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Mercury (Heavy Metal)', 'mercury-heavy-metal-152', 'Electrolytes', 'Comprehensive Mercury (Heavy Metal) test.', 'Mercury (Heavy Metal) analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Vitamin D (25-OH)', 'vitamin-d-25-oh-153', 'Vitamins', 'Comprehensive Vitamin D (25-OH) test.', 'Vitamin D (25-OH) analysis.', 279, 363, 'Blood', 0, '48hr', true),
('Vitamin D3 (1,25-OH)', 'vitamin-d3-1-25-oh-154', 'Vitamins', 'Comprehensive Vitamin D3 (1,25-OH) test.', 'Vitamin D3 (1,25-OH) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin B12', 'vitamin-b12-155', 'Vitamins', 'Comprehensive Vitamin B12 test.', 'Vitamin B12 analysis.', 249, 324, 'Blood', 0, '24hr', true),
('Folate (Vitamin B9)', 'folate-vitamin-b9-156', 'Vitamins', 'Comprehensive Folate (Vitamin B9) test.', 'Folate (Vitamin B9) analysis.', 249, 324, 'Blood', 0, '24hr', true),
('Vitamin A (Retinol)', 'vitamin-a-retinol-157', 'Vitamins', 'Comprehensive Vitamin A (Retinol) test.', 'Vitamin A (Retinol) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin E (Tocopherol)', 'vitamin-e-tocopherol-158', 'Vitamins', 'Comprehensive Vitamin E (Tocopherol) test.', 'Vitamin E (Tocopherol) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin K', 'vitamin-k-159', 'Vitamins', 'Comprehensive Vitamin K test.', 'Vitamin K analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Vitamin B1 (Thiamine)', 'vitamin-b1-thiamine-160', 'Vitamins', 'Comprehensive Vitamin B1 (Thiamine) test.', 'Vitamin B1 (Thiamine) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin B2 (Riboflavin)', 'vitamin-b2-riboflavin-161', 'Vitamins', 'Comprehensive Vitamin B2 (Riboflavin) test.', 'Vitamin B2 (Riboflavin) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin B3 (Niacin)', 'vitamin-b3-niacin-162', 'Vitamins', 'Comprehensive Vitamin B3 (Niacin) test.', 'Vitamin B3 (Niacin) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin B5 (Pantothenic Acid)', 'vitamin-b5-pantothenic-acid-163', 'Vitamins', 'Comprehensive Vitamin B5 (Pantothenic Acid) test.', 'Vitamin B5 (Pantothenic Acid) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin B6 (Pyridoxine)', 'vitamin-b6-pyridoxine-164', 'Vitamins', 'Comprehensive Vitamin B6 (Pyridoxine) test.', 'Vitamin B6 (Pyridoxine) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin B7 (Biotin)', 'vitamin-b7-biotin-165', 'Vitamins', 'Comprehensive Vitamin B7 (Biotin) test.', 'Vitamin B7 (Biotin) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Vitamin C (Ascorbic Acid)', 'vitamin-c-ascorbic-acid-166', 'Vitamins', 'Comprehensive Vitamin C (Ascorbic Acid) test.', 'Vitamin C (Ascorbic Acid) analysis.', 349, 454, 'Blood', 0, '48hr', true),
('Ferritin', 'ferritin-167', 'Vitamins', 'Comprehensive Ferritin test.', 'Ferritin analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Prolactin', 'prolactin-168', 'Hormones', 'Comprehensive Prolactin test.', 'Prolactin analysis.', 349, 454, 'Blood', 0, '24hr', true),
('LH (Luteinizing Hormone)', 'lh-luteinizing-hormone-169', 'Hormones', 'Comprehensive LH (Luteinizing Hormone) test.', 'LH (Luteinizing Hormone) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('FSH (Follicle Stimulating Hormone)', 'fsh-follicle-stimulating-hormone-170', 'Hormones', 'Comprehensive FSH (Follicle Stimulating Hormone) test.', 'FSH (Follicle Stimulating Hormone) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Estradiol (E2)', 'estradiol-e2-171', 'Hormones', 'Comprehensive Estradiol (E2) test.', 'Estradiol (E2) analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Progesterone', 'progesterone-172', 'Hormones', 'Comprehensive Progesterone test.', 'Progesterone analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Testosterone (Total)', 'testosterone-total-173', 'Hormones', 'Comprehensive Testosterone (Total) test.', 'Testosterone (Total) analysis.', 399, 519, 'Blood', 0, '24hr', true),
('Testosterone (Free)', 'testosterone-free-174', 'Hormones', 'Comprehensive Testosterone (Free) test.', 'Testosterone (Free) analysis.', 499, 649, 'Blood', 0, '24hr', true),
('DHEA-S', 'dhea-s-175', 'Hormones', 'Comprehensive DHEA-S test.', 'DHEA-S analysis.', 399, 519, 'Blood', 0, '24hr', true),
('Androstenedione', 'androstenedione-176', 'Hormones', 'Comprehensive Androstenedione test.', 'Androstenedione analysis.', 399, 519, 'Blood', 0, '24hr', true),
('SHBG', 'shbg-177', 'Hormones', 'Comprehensive SHBG test.', 'SHBG analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Cortisol (Morning)', 'cortisol-morning-178', 'Hormones', 'Comprehensive Cortisol (Morning) test.', 'Cortisol (Morning) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Cortisol (Evening)', 'cortisol-evening-179', 'Hormones', 'Comprehensive Cortisol (Evening) test.', 'Cortisol (Evening) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('ACTH', 'acth-180', 'Hormones', 'Comprehensive ACTH test.', 'ACTH analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Aldosterone', 'aldosterone-181', 'Hormones', 'Comprehensive Aldosterone test.', 'Aldosterone analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Renin', 'renin-182', 'Hormones', 'Comprehensive Renin test.', 'Renin analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Aldosterone/Renin Ratio', 'aldosterone-renin-ratio-183', 'Hormones', 'Comprehensive Aldosterone/Renin Ratio test.', 'Aldosterone/Renin Ratio analysis.', 599, 779, 'Blood', 0, '48hr', true),
('PTH (Parathyroid Hormone)', 'pth-parathyroid-hormone-184', 'Hormones', 'Comprehensive PTH (Parathyroid Hormone) test.', 'PTH (Parathyroid Hormone) analysis.', 449, 584, 'Blood', 0, '24hr', true),
('Growth Hormone (GH)', 'growth-hormone-gh-185', 'Hormones', 'Comprehensive Growth Hormone (GH) test.', 'Growth Hormone (GH) analysis.', 499, 649, 'Blood', 0, '24hr', true),
('IGF-1 (Somatomedin C)', 'igf-1-somatomedin-c-186', 'Hormones', 'Comprehensive IGF-1 (Somatomedin C) test.', 'IGF-1 (Somatomedin C) analysis.', 499, 649, 'Blood', 0, '48hr', true),
('IGFBP-3', 'igfbp-3-187', 'Hormones', 'Comprehensive IGFBP-3 test.', 'IGFBP-3 analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Anti-Mullerian Hormone (AMH)', 'anti-mullerian-hormone-amh-188', 'Hormones', 'Comprehensive Anti-Mullerian Hormone (AMH) test.', 'Anti-Mullerian Hormone (AMH) analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('Inhibin A', 'inhibin-a-189', 'Hormones', 'Comprehensive Inhibin A test.', 'Inhibin A analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Inhibin B', 'inhibin-b-190', 'Hormones', 'Comprehensive Inhibin B test.', 'Inhibin B analysis.', 599, 779, 'Blood', 0, '48hr', true),
('17-Hydroxyprogesterone', '17-hydroxyprogesterone-191', 'Hormones', 'Comprehensive 17-Hydroxyprogesterone test.', '17-Hydroxyprogesterone analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Androgen Index (FAI)', 'androgen-index-fai-192', 'Hormones', 'Comprehensive Androgen Index (FAI) test.', 'Androgen Index (FAI) analysis.', 449, 584, 'Blood', 0, '24hr', true),
('Metanephrines (Plasma)', 'metanephrines-plasma-193', 'Hormones', 'Comprehensive Metanephrines (Plasma) test.', 'Metanephrines (Plasma) analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('Normetanephrines', 'normetanephrines-194', 'Hormones', 'Comprehensive Normetanephrines test.', 'Normetanephrines analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('Chromogranin A', 'chromogranin-a-195', 'Hormones', 'Comprehensive Chromogranin A test.', 'Chromogranin A analysis.', 799, 1039, 'Blood', 0, '48hr', true),
('Serotonin', 'serotonin-196', 'Hormones', 'Comprehensive Serotonin test.', 'Serotonin analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Melatonin', 'melatonin-197', 'Hormones', 'Comprehensive Melatonin test.', 'Melatonin analysis.', 599, 779, 'Blood', 0, '48hr', true),
('HIV 1 & 2 Antibody (Rapid)', 'hiv-1-2-antibody-rapid-198', 'Serology', 'Comprehensive HIV 1 & 2 Antibody (Rapid) test.', 'HIV 1 & 2 Antibody (Rapid) analysis.', 399, 519, 'Blood', 0, '2hr', true),
('HIV ELISA (4th Gen)', 'hiv-elisa-4th-gen-199', 'Serology', 'Comprehensive HIV ELISA (4th Gen) test.', 'HIV ELISA (4th Gen) analysis.', 449, 584, 'Blood', 0, '24hr', true),
('HIV Western Blot', 'hiv-western-blot-200', 'Serology', 'Comprehensive HIV Western Blot test.', 'HIV Western Blot analysis.', 1499, 1949, 'Blood', 0, '72hr', true),
('HIV Viral Load (PCR)', 'hiv-viral-load-pcr-201', 'Serology', 'Comprehensive HIV Viral Load (PCR) test.', 'HIV Viral Load (PCR) analysis.', 2499, 3249, 'Blood', 0, '72hr', true),
('HIV Early Infant Diagnosis', 'hiv-early-infant-diagnosis-202', 'Serology', 'Comprehensive HIV Early Infant Diagnosis test.', 'HIV Early Infant Diagnosis analysis.', 1999, 2599, 'Blood', 0, '72hr', true),
('Hepatitis B Surface Antigen (HBsAg)', 'hepatitis-b-surface-antigen-hbsag-203', 'Serology', 'Comprehensive Hepatitis B Surface Antigen (HBsAg) test.', 'Hepatitis B Surface Antigen (HBsAg) analysis.', 279, 363, 'Blood', 0, '1hr', true),
('Hepatitis B Surface Antibody (Anti-HBs)', 'hepatitis-b-surface-antibody-anti-hbs-204', 'Serology', 'Comprehensive Hepatitis B Surface Antibody (Anti-HBs) test.', 'Hepatitis B Surface Antibody (Anti-HBs) analysis.', 279, 363, 'Blood', 0, '1hr', true),
('Hepatitis B Core Antibody (Anti-HBc)', 'hepatitis-b-core-antibody-anti-hbc-205', 'Serology', 'Comprehensive Hepatitis B Core Antibody (Anti-HBc) test.', 'Hepatitis B Core Antibody (Anti-HBc) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Hepatitis B e Antigen (HBeAg)', 'hepatitis-b-e-antigen-hbeag-206', 'Serology', 'Comprehensive Hepatitis B e Antigen (HBeAg) test.', 'Hepatitis B e Antigen (HBeAg) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Hepatitis B e Antibody (Anti-HBe)', 'hepatitis-b-e-antibody-anti-hbe-207', 'Serology', 'Comprehensive Hepatitis B e Antibody (Anti-HBe) test.', 'Hepatitis B e Antibody (Anti-HBe) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('HBV DNA Quantitative', 'hbv-dna-quantitative-208', 'Serology', 'Comprehensive HBV DNA Quantitative test.', 'HBV DNA Quantitative analysis.', 1999, 2599, 'Blood', 0, '72hr', true),
('Hepatitis C Antibody (Anti-HCV)', 'hepatitis-c-antibody-anti-hcv-209', 'Serology', 'Comprehensive Hepatitis C Antibody (Anti-HCV) test.', 'Hepatitis C Antibody (Anti-HCV) analysis.', 349, 454, 'Blood', 0, '1hr', true),
('HCV RNA Quantitative', 'hcv-rna-quantitative-210', 'Serology', 'Comprehensive HCV RNA Quantitative test.', 'HCV RNA Quantitative analysis.', 1999, 2599, 'Blood', 0, '72hr', true),
('HCV Genotyping', 'hcv-genotyping-211', 'Serology', 'Comprehensive HCV Genotyping test.', 'HCV Genotyping analysis.', 2999, 3899, 'Blood', 0, '96hr', true),
('Hepatitis A IgM', 'hepatitis-a-igm-212', 'Serology', 'Comprehensive Hepatitis A IgM test.', 'Hepatitis A IgM analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Hepatitis A IgG', 'hepatitis-a-igg-213', 'Serology', 'Comprehensive Hepatitis A IgG test.', 'Hepatitis A IgG analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Hepatitis E IgM', 'hepatitis-e-igm-214', 'Serology', 'Comprehensive Hepatitis E IgM test.', 'Hepatitis E IgM analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Hepatitis E IgG', 'hepatitis-e-igg-215', 'Serology', 'Comprehensive Hepatitis E IgG test.', 'Hepatitis E IgG analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Hepatitis D Antibody', 'hepatitis-d-antibody-216', 'Serology', 'Comprehensive Hepatitis D Antibody test.', 'Hepatitis D Antibody analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Syphilis (VDRL/RPR)', 'syphilis-vdrl-rpr-217', 'Serology', 'Comprehensive Syphilis (VDRL/RPR) test.', 'Syphilis (VDRL/RPR) analysis.', 199, 259, 'Blood', 0, '2hr', true),
('Syphilis (TPHA)', 'syphilis-tpha-218', 'Serology', 'Comprehensive Syphilis (TPHA) test.', 'Syphilis (TPHA) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Syphilis (FTA-ABS)', 'syphilis-fta-abs-219', 'Serology', 'Comprehensive Syphilis (FTA-ABS) test.', 'Syphilis (FTA-ABS) analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Dengue NS1 Antigen', 'dengue-ns1-antigen-220', 'Serology', 'Comprehensive Dengue NS1 Antigen test.', 'Dengue NS1 Antigen analysis.', 349, 454, 'Blood', 0, '2hr', true),
('Dengue IgM Antibody', 'dengue-igm-antibody-221', 'Serology', 'Comprehensive Dengue IgM Antibody test.', 'Dengue IgM Antibody analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Dengue IgG Antibody', 'dengue-igg-antibody-222', 'Serology', 'Comprehensive Dengue IgG Antibody test.', 'Dengue IgG Antibody analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Chikungunya IgM', 'chikungunya-igm-223', 'Serology', 'Comprehensive Chikungunya IgM test.', 'Chikungunya IgM analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Chikungunya IgG', 'chikungunya-igg-224', 'Serology', 'Comprehensive Chikungunya IgG test.', 'Chikungunya IgG analysis.', 349, 454, 'Blood', 0, '24hr', true),
('Malaria Antigen (Pf/Pv)', 'malaria-antigen-pf-pv-225', 'Serology', 'Comprehensive Malaria Antigen (Pf/Pv) test.', 'Malaria Antigen (Pf/Pv) analysis.', 199, 259, 'Blood', 0, '1hr', true),
('Malaria (Thick/Thin Smear)', 'malaria-thick-thin-smear-226', 'Serology', 'Comprehensive Malaria (Thick/Thin Smear) test.', 'Malaria (Thick/Thin Smear) analysis.', 149, 194, 'Blood', 0, '2hr', true),
('Typhoid (Widal Test)', 'typhoid-widal-test-227', 'Serology', 'Comprehensive Typhoid (Widal Test) test.', 'Typhoid (Widal Test) analysis.', 199, 259, 'Blood', 0, '24hr', true),
('Typhoid (IgM/IgG)', 'typhoid-igm-igg-228', 'Serology', 'Comprehensive Typhoid (IgM/IgG) test.', 'Typhoid (IgM/IgG) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Typhoid (Blood Culture)', 'typhoid-blood-culture-229', 'Serology', 'Comprehensive Typhoid (Blood Culture) test.', 'Typhoid (Blood Culture) analysis.', 399, 519, 'Blood', 0, '72hr', true),
('Leptospira IgM', 'leptospira-igm-230', 'Serology', 'Comprehensive Leptospira IgM test.', 'Leptospira IgM analysis.', 399, 519, 'Blood', 0, '24hr', true),
('Scrub Typhus IgM', 'scrub-typhus-igm-231', 'Serology', 'Comprehensive Scrub Typhus IgM test.', 'Scrub Typhus IgM analysis.', 399, 519, 'Blood', 0, '24hr', true),
('Japanese Encephalitis IgM', 'japanese-encephalitis-igm-232', 'Serology', 'Comprehensive Japanese Encephalitis IgM test.', 'Japanese Encephalitis IgM analysis.', 449, 584, 'Blood', 0, '48hr', true),
('COVID-19 RT-PCR', 'covid-19-rt-pcr-233', 'Serology', 'Comprehensive COVID-19 RT-PCR test.', 'COVID-19 RT-PCR analysis.', 499, 649, 'Blood', 0, '24hr', true),
('COVID-19 Antigen', 'covid-19-antigen-234', 'Serology', 'Comprehensive COVID-19 Antigen test.', 'COVID-19 Antigen analysis.', 199, 259, 'Blood', 0, '1hr', true),
('COVID-19 Antibody (IgG/IgM)', 'covid-19-antibody-igg-igm-235', 'Serology', 'Comprehensive COVID-19 Antibody (IgG/IgM) test.', 'COVID-19 Antibody (IgG/IgM) analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Influenza A/B Antigen', 'influenza-a-b-antigen-236', 'Serology', 'Comprehensive Influenza A/B Antigen test.', 'Influenza A/B Antigen analysis.', 399, 519, 'Blood', 0, '2hr', true),
('RSV Antigen', 'rsv-antigen-237', 'Serology', 'Comprehensive RSV Antigen test.', 'RSV Antigen analysis.', 399, 519, 'Blood', 0, '2hr', true),
('ANA (Antinuclear Antibody)', 'ana-antinuclear-antibody-238', 'Autoimmune', 'Comprehensive ANA (Antinuclear Antibody) test.', 'ANA (Antinuclear Antibody) analysis.', 399, 519, 'Blood', 0, '72hr', true),
('ANA Profile (15 parameters)', 'ana-profile-15-parameters-239', 'Autoimmune', 'Comprehensive ANA Profile (15 parameters) test.', 'ANA Profile (15 parameters) analysis.', 1499, 1949, 'Blood', 0, '96hr', true),
('dsDNA Antibody', 'dsdna-antibody-240', 'Autoimmune', 'Comprehensive dsDNA Antibody test.', 'dsDNA Antibody analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Rheumatoid Factor (RF)', 'rheumatoid-factor-rf-241', 'Autoimmune', 'Comprehensive Rheumatoid Factor (RF) test.', 'Rheumatoid Factor (RF) analysis.', 199, 259, 'Blood', 0, '1hr', true),
('Anti-CCP Antibody', 'anti-ccp-antibody-242', 'Autoimmune', 'Comprehensive Anti-CCP Antibody test.', 'Anti-CCP Antibody analysis.', 499, 649, 'Blood', 0, '48hr', true),
('ESR (Autoimmune Monitoring)', 'esr-autoimmune-monitoring-243', 'Autoimmune', 'Comprehensive ESR (Autoimmune Monitoring) test.', 'ESR (Autoimmune Monitoring) analysis.', 149, 194, 'Blood', 0, '2hr', true),
('CRP (Quantitative)', 'crp-quantitative-244', 'Autoimmune', 'Comprehensive CRP (Quantitative) test.', 'CRP (Quantitative) analysis.', 149, 194, 'Blood', 0, '24hr', true),
('hs-CRP', 'hs-crp-245', 'Autoimmune', 'Comprehensive hs-CRP test.', 'hs-CRP analysis.', 249, 324, 'Blood', 0, '24hr', true),
('ANCA (cANCA/pANCA)', 'anca-canca-panca-246', 'Autoimmune', 'Comprehensive ANCA (cANCA/pANCA) test.', 'ANCA (cANCA/pANCA) analysis.', 699, 909, 'Blood', 0, '72hr', true),
('Anti-MPO', 'anti-mpo-247', 'Autoimmune', 'Comprehensive Anti-MPO test.', 'Anti-MPO analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Anti-PR3', 'anti-pr3-248', 'Autoimmune', 'Comprehensive Anti-PR3 test.', 'Anti-PR3 analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Anti-Smith Antibody', 'anti-smith-antibody-249', 'Autoimmune', 'Comprehensive Anti-Smith Antibody test.', 'Anti-Smith Antibody analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Anti-Ro/SSA Antibody', 'anti-ro-ssa-antibody-250', 'Autoimmune', 'Comprehensive Anti-Ro/SSA Antibody test.', 'Anti-Ro/SSA Antibody analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Anti-La/SSB Antibody', 'anti-la-ssb-antibody-251', 'Autoimmune', 'Comprehensive Anti-La/SSB Antibody test.', 'Anti-La/SSB Antibody analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Anti-Scl-70', 'anti-scl-70-252', 'Autoimmune', 'Comprehensive Anti-Scl-70 test.', 'Anti-Scl-70 analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Anti-Jo-1', 'anti-jo-1-253', 'Autoimmune', 'Comprehensive Anti-Jo-1 test.', 'Anti-Jo-1 analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Anti-RNP', 'anti-rnp-254', 'Autoimmune', 'Comprehensive Anti-RNP test.', 'Anti-RNP analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Total IgE', 'total-ige-255', 'Autoimmune', 'Comprehensive Total IgE test.', 'Total IgE analysis.', 299, 389, 'Blood', 0, '24hr', true),
('Allergen Specific IgE (Food)', 'allergen-specific-ige-food-256', 'Autoimmune', 'Comprehensive Allergen Specific IgE (Food) test.', 'Allergen Specific IgE (Food) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Allergen Specific IgE (Inhalants)', 'allergen-specific-ige-inhalants-257', 'Autoimmune', 'Comprehensive Allergen Specific IgE (Inhalants) test.', 'Allergen Specific IgE (Inhalants) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Food Intolerance Test (100 items)', 'food-intolerance-test-100-items-258', 'Autoimmune', 'Comprehensive Food Intolerance Test (100 items) test.', 'Food Intolerance Test (100 items) analysis.', 3999, 5199, 'Blood', 0, '96hr', true),
('Celiac Disease Panel', 'celiac-disease-panel-259', 'Autoimmune', 'Comprehensive Celiac Disease Panel test.', 'Celiac Disease Panel analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('Tissue Transglutaminase IgA', 'tissue-transglutaminase-iga-260', 'Autoimmune', 'Comprehensive Tissue Transglutaminase IgA test.', 'Tissue Transglutaminase IgA analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Endomysial Antibody', 'endomysial-antibody-261', 'Autoimmune', 'Comprehensive Endomysial Antibody test.', 'Endomysial Antibody analysis.', 499, 649, 'Blood', 0, '48hr', true),
('Anti-Gliadin Antibody', 'anti-gliadin-antibody-262', 'Autoimmune', 'Comprehensive Anti-Gliadin Antibody test.', 'Anti-Gliadin Antibody analysis.', 399, 519, 'Blood', 0, '48hr', true),
('CEA (Carcinoembryonic Antigen)', 'cea-carcinoembryonic-antigen-263', 'Tumor Markers', 'Comprehensive CEA (Carcinoembryonic Antigen) test.', 'CEA (Carcinoembryonic Antigen) analysis.', 399, 519, 'Blood', 0, '24hr', true),
('CA 125 (Ovarian Cancer)', 'ca-125-ovarian-cancer-264', 'Tumor Markers', 'Comprehensive CA 125 (Ovarian Cancer) test.', 'CA 125 (Ovarian Cancer) analysis.', 449, 584, 'Blood', 0, '24hr', true),
('CA 15-3 (Breast Cancer)', 'ca-15-3-breast-cancer-265', 'Tumor Markers', 'Comprehensive CA 15-3 (Breast Cancer) test.', 'CA 15-3 (Breast Cancer) analysis.', 449, 584, 'Blood', 0, '24hr', true),
('CA 19-9 (Pancreatic Cancer)', 'ca-19-9-pancreatic-cancer-266', 'Tumor Markers', 'Comprehensive CA 19-9 (Pancreatic Cancer) test.', 'CA 19-9 (Pancreatic Cancer) analysis.', 449, 584, 'Blood', 0, '24hr', true),
('CA 72-4 (Gastric Cancer)', 'ca-72-4-gastric-cancer-267', 'Tumor Markers', 'Comprehensive CA 72-4 (Gastric Cancer) test.', 'CA 72-4 (Gastric Cancer) analysis.', 499, 649, 'Blood', 0, '48hr', true),
('AFP (Liver Cancer)', 'afp-liver-cancer-268', 'Tumor Markers', 'Comprehensive AFP (Liver Cancer) test.', 'AFP (Liver Cancer) analysis.', 399, 519, 'Blood', 0, '24hr', true),
('PSA (Prostate Cancer)', 'psa-prostate-cancer-269', 'Tumor Markers', 'Comprehensive PSA (Prostate Cancer) test.', 'PSA (Prostate Cancer) analysis.', 399, 519, 'Blood', 0, '24hr', true),
('Free PSA', 'free-psa-270', 'Tumor Markers', 'Comprehensive Free PSA test.', 'Free PSA analysis.', 499, 649, 'Blood', 0, '24hr', true),
('PSA Ratio', 'psa-ratio-271', 'Tumor Markers', 'Comprehensive PSA Ratio test.', 'PSA Ratio analysis.', 599, 779, 'Blood', 0, '24hr', true),
('Beta-hCG (Tumor Marker)', 'beta-hcg-tumor-marker-272', 'Tumor Markers', 'Comprehensive Beta-hCG (Tumor Marker) test.', 'Beta-hCG (Tumor Marker) analysis.', 399, 519, 'Blood', 0, '24hr', true),
('NSE (Lung Cancer)', 'nse-lung-cancer-273', 'Tumor Markers', 'Comprehensive NSE (Lung Cancer) test.', 'NSE (Lung Cancer) analysis.', 499, 649, 'Blood', 0, '48hr', true),
('CYFRA 21-1', 'cyfra-21-1-274', 'Tumor Markers', 'Comprehensive CYFRA 21-1 test.', 'CYFRA 21-1 analysis.', 499, 649, 'Blood', 0, '48hr', true),
('SCC Antigen', 'scc-antigen-275', 'Tumor Markers', 'Comprehensive SCC Antigen test.', 'SCC Antigen analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Thyroglobulin (Thyroid Cancer)', 'thyroglobulin-thyroid-cancer-276', 'Tumor Markers', 'Comprehensive Thyroglobulin (Thyroid Cancer) test.', 'Thyroglobulin (Thyroid Cancer) analysis.', 399, 519, 'Blood', 0, '48hr', true),
('Calcitonin (Medullary Thyroid)', 'calcitonin-medullary-thyroid-277', 'Tumor Markers', 'Comprehensive Calcitonin (Medullary Thyroid) test.', 'Calcitonin (Medullary Thyroid) analysis.', 599, 779, 'Blood', 0, '48hr', true),
('HE4 (Ovarian Cancer)', 'he4-ovarian-cancer-278', 'Tumor Markers', 'Comprehensive HE4 (Ovarian Cancer) test.', 'HE4 (Ovarian Cancer) analysis.', 599, 779, 'Blood', 0, '48hr', true),
('ROMA Index', 'roma-index-279', 'Tumor Markers', 'Comprehensive ROMA Index test.', 'ROMA Index analysis.', 799, 1039, 'Blood', 0, '48hr', true),
('Chromogranin A', 'chromogranin-a-280', 'Tumor Markers', 'Comprehensive Chromogranin A test.', 'Chromogranin A analysis.', 799, 1039, 'Blood', 0, '48hr', true),
('Beta-2 Microglobulin', 'beta-2-microglobulin-281', 'Tumor Markers', 'Comprehensive Beta-2 Microglobulin test.', 'Beta-2 Microglobulin analysis.', 399, 519, 'Blood', 0, '24hr', true),
('LDH (Tumor Marker)', 'ldh-tumor-marker-282', 'Tumor Markers', 'Comprehensive LDH (Tumor Marker) test.', 'LDH (Tumor Marker) analysis.', 149, 194, 'Blood', 0, '2hr', true),
('Amylase', 'amylase-283', 'Digestive', 'Comprehensive Amylase test.', 'Amylase analysis.', 179, 233, 'Blood', 0, '1hr', true),
('Lipase', 'lipase-284', 'Digestive', 'Comprehensive Lipase test.', 'Lipase analysis.', 179, 233, 'Blood', 0, '1hr', true),
('Pancreatic Elastase (Stool)', 'pancreatic-elastase-stool-285', 'Digestive', 'Comprehensive Pancreatic Elastase (Stool) test.', 'Pancreatic Elastase (Stool) analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Trypsinogen', 'trypsinogen-286', 'Digestive', 'Comprehensive Trypsinogen test.', 'Trypsinogen analysis.', 449, 584, 'Blood', 0, '48hr', true),
('Gastrin', 'gastrin-287', 'Digestive', 'Comprehensive Gastrin test.', 'Gastrin analysis.', 499, 649, 'Blood', 1, '48hr', true),
('Pepsinogen I & II', 'pepsinogen-i-ii-288', 'Digestive', 'Comprehensive Pepsinogen I & II test.', 'Pepsinogen I & II analysis.', 599, 779, 'Blood', 0, '48hr', true),
('Gastrin-Releasing Peptide', 'gastrin-releasing-peptide-289', 'Digestive', 'Comprehensive Gastrin-Releasing Peptide test.', 'Gastrin-Releasing Peptide analysis.', 699, 909, 'Blood', 0, '48hr', true),
('VIP (Vasoactive Intestinal Peptide)', 'vip-vasoactive-intestinal-peptide-290', 'Digestive', 'Comprehensive VIP (Vasoactive Intestinal Peptide) test.', 'VIP (Vasoactive Intestinal Peptide) analysis.', 799, 1039, 'Blood', 0, '48hr', true),
('Somatostatin', 'somatostatin-291', 'Digestive', 'Comprehensive Somatostatin test.', 'Somatostatin analysis.', 799, 1039, 'Blood', 0, '48hr', true),
('Substance P', 'substance-p-292', 'Digestive', 'Comprehensive Substance P test.', 'Substance P analysis.', 699, 909, 'Blood', 0, '48hr', true),
('Urine Routine (Complete)', 'urine-routine-complete-293', 'Urine', 'Comprehensive Urine Routine (Complete) test.', 'Urine Routine (Complete) analysis.', 149, 194, 'Urine', 0, '24hr', true),
('Urine Microscopy', 'urine-microscopy-294', 'Urine', 'Comprehensive Urine Microscopy test.', 'Urine Microscopy analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Albumin', 'urine-albumin-295', 'Urine', 'Comprehensive Urine Albumin test.', 'Urine Albumin analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Sugar (Glucose)', 'urine-sugar-glucose-296', 'Urine', 'Comprehensive Urine Sugar (Glucose) test.', 'Urine Sugar (Glucose) analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Ketone Bodies', 'urine-ketone-bodies-297', 'Urine', 'Comprehensive Urine Ketone Bodies test.', 'Urine Ketone Bodies analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Bile Salts', 'urine-bile-salts-298', 'Urine', 'Comprehensive Urine Bile Salts test.', 'Urine Bile Salts analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Bile Pigments', 'urine-bile-pigments-299', 'Urine', 'Comprehensive Urine Bile Pigments test.', 'Urine Bile Pigments analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine pH', 'urine-ph-300', 'Urine', 'Comprehensive Urine pH test.', 'Urine pH analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Specific Gravity', 'urine-specific-gravity-301', 'Urine', 'Comprehensive Urine Specific Gravity test.', 'Urine Specific Gravity analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Urobilinogen', 'urine-urobilinogen-302', 'Urine', 'Comprehensive Urine Urobilinogen test.', 'Urine Urobilinogen analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Nitrite', 'urine-nitrite-303', 'Urine', 'Comprehensive Urine Nitrite test.', 'Urine Nitrite analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Leukocyte Esterase', 'urine-leukocyte-esterase-304', 'Urine', 'Comprehensive Urine Leukocyte Esterase test.', 'Urine Leukocyte Esterase analysis.', 99, 129, 'Urine', 0, '2hr', true),
('Urine Pregnancy Test', 'urine-pregnancy-test-305', 'Urine', 'Comprehensive Urine Pregnancy Test test.', 'Urine Pregnancy Test analysis.', 99, 129, 'Urine', 0, '30min', true),
('Urine Microalbumin', 'urine-microalbumin-306', 'Urine', 'Comprehensive Urine Microalbumin test.', 'Urine Microalbumin analysis.', 199, 259, 'Urine', 0, '24hr', true),
('Urine Protein/Creatinine Ratio', 'urine-protein-creatinine-ratio-307', 'Urine', 'Comprehensive Urine Protein/Creatinine Ratio test.', 'Urine Protein/Creatinine Ratio analysis.', 249, 324, 'Urine', 0, '24hr', true),
('Urine Albumin/Creatinine Ratio', 'urine-albumin-creatinine-ratio-308', 'Urine', 'Comprehensive Urine Albumin/Creatinine Ratio test.', 'Urine Albumin/Creatinine Ratio analysis.', 249, 324, 'Urine', 0, '24hr', true),
('24-Hour Urine Protein', '24-hour-urine-protein-309', 'Urine', 'Comprehensive 24-Hour Urine Protein test.', '24-Hour Urine Protein analysis.', 299, 389, 'Urine', 0, '48hr', true),
('24-Hour Urine Creatinine', '24-hour-urine-creatinine-310', 'Urine', 'Comprehensive 24-Hour Urine Creatinine test.', '24-Hour Urine Creatinine analysis.', 199, 259, 'Urine', 0, '48hr', true),
('24-Hour Urine Urea', '24-hour-urine-urea-311', 'Urine', 'Comprehensive 24-Hour Urine Urea test.', '24-Hour Urine Urea analysis.', 199, 259, 'Urine', 0, '48hr', true),
('24-Hour Urine Uric Acid', '24-hour-urine-uric-acid-312', 'Urine', 'Comprehensive 24-Hour Urine Uric Acid test.', '24-Hour Urine Uric Acid analysis.', 199, 259, 'Urine', 0, '48hr', true),
('24-Hour Urine Calcium', '24-hour-urine-calcium-313', 'Urine', 'Comprehensive 24-Hour Urine Calcium test.', '24-Hour Urine Calcium analysis.', 199, 259, 'Urine', 0, '48hr', true),
('24-Hour Urine Phosphorus', '24-hour-urine-phosphorus-314', 'Urine', 'Comprehensive 24-Hour Urine Phosphorus test.', '24-Hour Urine Phosphorus analysis.', 199, 259, 'Urine', 0, '48hr', true),
('24-Hour Urine Sodium', '24-hour-urine-sodium-315', 'Urine', 'Comprehensive 24-Hour Urine Sodium test.', '24-Hour Urine Sodium analysis.', 199, 259, 'Urine', 0, '48hr', true),
('24-Hour Urine Potassium', '24-hour-urine-potassium-316', 'Urine', 'Comprehensive 24-Hour Urine Potassium test.', '24-Hour Urine Potassium analysis.', 199, 259, 'Urine', 0, '48hr', true),
('24-Hour Urine Chloride', '24-hour-urine-chloride-317', 'Urine', 'Comprehensive 24-Hour Urine Chloride test.', '24-Hour Urine Chloride analysis.', 199, 259, 'Urine', 0, '48hr', true),
('24-Hour Urine Magnesium', '24-hour-urine-magnesium-318', 'Urine', 'Comprehensive 24-Hour Urine Magnesium test.', '24-Hour Urine Magnesium analysis.', 249, 324, 'Urine', 0, '48hr', true),
('24-Hour Urine Oxalate', '24-hour-urine-oxalate-319', 'Urine', 'Comprehensive 24-Hour Urine Oxalate test.', '24-Hour Urine Oxalate analysis.', 349, 454, 'Urine', 0, '48hr', true),
('24-Hour Urine Citrate', '24-hour-urine-citrate-320', 'Urine', 'Comprehensive 24-Hour Urine Citrate test.', '24-Hour Urine Citrate analysis.', 349, 454, 'Urine', 0, '48hr', true),
('Urine Culture & Sensitivity', 'urine-culture-sensitivity-321', 'Urine', 'Comprehensive Urine Culture & Sensitivity test.', 'Urine Culture & Sensitivity analysis.', 399, 519, 'Urine', 0, '72hr', true),
('Urine AFB (TB)', 'urine-afb-tb-322', 'Urine', 'Comprehensive Urine AFB (TB) test.', 'Urine AFB (TB) analysis.', 299, 389, 'Urine', 0, '72hr', true),
('Urine for Fungal Culture', 'urine-for-fungal-culture-323', 'Urine', 'Comprehensive Urine for Fungal Culture test.', 'Urine for Fungal Culture analysis.', 399, 519, 'Urine', 0, '96hr', true),
('Urine Cytology', 'urine-cytology-324', 'Urine', 'Comprehensive Urine Cytology test.', 'Urine Cytology analysis.', 449, 584, 'Urine', 0, '48hr', true),
('Urine Bence Jones Protein', 'urine-bence-jones-protein-325', 'Urine', 'Comprehensive Urine Bence Jones Protein test.', 'Urine Bence Jones Protein analysis.', 349, 454, 'Urine', 0, '48hr', true),
('Urine Electrolytes', 'urine-electrolytes-326', 'Urine', 'Comprehensive Urine Electrolytes test.', 'Urine Electrolytes analysis.', 199, 259, 'Urine', 0, '24hr', true),
('Urine Osmolality', 'urine-osmolality-327', 'Urine', 'Comprehensive Urine Osmolality test.', 'Urine Osmolality analysis.', 199, 259, 'Urine', 0, '24hr', true),
('Urine Copper (Wilson''s)', 'urine-copper-wilson-s-328', 'Urine', 'Comprehensive Urine Copper (Wilson''s) test.', 'Urine Copper (Wilson''s) analysis.', 399, 519, 'Urine', 0, '48hr', true),
('Urine Porphobilinogen', 'urine-porphobilinogen-329', 'Urine', 'Comprehensive Urine Porphobilinogen test.', 'Urine Porphobilinogen analysis.', 299, 389, 'Urine', 0, '24hr', true),
('Urine 5-HIAA', 'urine-5-hiaa-330', 'Urine', 'Comprehensive Urine 5-HIAA test.', 'Urine 5-HIAA analysis.', 449, 584, 'Urine', 0, '48hr', true),
('Urine Metanephrines', 'urine-metanephrines-331', 'Urine', 'Comprehensive Urine Metanephrines test.', 'Urine Metanephrines analysis.', 899, 1169, 'Urine', 0, '48hr', true),
('Urine Cortisol (Free)', 'urine-cortisol-free-332', 'Urine', 'Comprehensive Urine Cortisol (Free) test.', 'Urine Cortisol (Free) analysis.', 599, 779, 'Urine', 0, '48hr', true),
('X-Ray Chest PA View', 'x-ray-chest-pa-view-333', 'X-Ray', 'Comprehensive X-Ray Chest PA View test.', 'X-Ray Chest PA View analysis.', 171, 222, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Chest AP View', 'x-ray-chest-ap-view-334', 'X-Ray', 'Comprehensive X-Ray Chest AP View test.', 'X-Ray Chest AP View analysis.', 171, 222, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Abdomen AP View', 'x-ray-abdomen-ap-view-335', 'X-Ray', 'Comprehensive X-Ray Abdomen AP View test.', 'X-Ray Abdomen AP View analysis.', 171, 222, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Abdomen Erect', 'x-ray-abdomen-erect-336', 'X-Ray', 'Comprehensive X-Ray Abdomen Erect test.', 'X-Ray Abdomen Erect analysis.', 171, 222, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Abdomen Supine', 'x-ray-abdomen-supine-337', 'X-Ray', 'Comprehensive X-Ray Abdomen Supine test.', 'X-Ray Abdomen Supine analysis.', 171, 222, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray KUB', 'x-ray-kub-338', 'X-Ray', 'Comprehensive X-Ray KUB test.', 'X-Ray KUB analysis.', 171, 222, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Lumbar Spine AP/LAT', 'x-ray-lumbar-spine-ap-lat-339', 'X-Ray', 'Comprehensive X-Ray Lumbar Spine AP/LAT test.', 'X-Ray Lumbar Spine AP/LAT analysis.', 249, 324, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Cervical Spine AP/LAT', 'x-ray-cervical-spine-ap-lat-340', 'X-Ray', 'Comprehensive X-Ray Cervical Spine AP/LAT test.', 'X-Ray Cervical Spine AP/LAT analysis.', 249, 324, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Thoracic Spine AP/LAT', 'x-ray-thoracic-spine-ap-lat-341', 'X-Ray', 'Comprehensive X-Ray Thoracic Spine AP/LAT test.', 'X-Ray Thoracic Spine AP/LAT analysis.', 249, 324, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Pelvis AP View', 'x-ray-pelvis-ap-view-342', 'X-Ray', 'Comprehensive X-Ray Pelvis AP View test.', 'X-Ray Pelvis AP View analysis.', 199, 259, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Hip Joint', 'x-ray-hip-joint-343', 'X-Ray', 'Comprehensive X-Ray Hip Joint test.', 'X-Ray Hip Joint analysis.', 199, 259, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Knee Joint', 'x-ray-knee-joint-344', 'X-Ray', 'Comprehensive X-Ray Knee Joint test.', 'X-Ray Knee Joint analysis.', 199, 259, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Ankle Joint', 'x-ray-ankle-joint-345', 'X-Ray', 'Comprehensive X-Ray Ankle Joint test.', 'X-Ray Ankle Joint analysis.', 199, 259, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Shoulder Joint', 'x-ray-shoulder-joint-346', 'X-Ray', 'Comprehensive X-Ray Shoulder Joint test.', 'X-Ray Shoulder Joint analysis.', 199, 259, 'Radiology/Imaging', 0, '12-72hr', true),
('X-Ray Wrist Joint', 'x-ray-wrist-joint-347', 'X-Ray', 'Comprehensive X-Ray Wrist Joint test.', 'X-Ray Wrist Joint analysis.', 199, 259, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Whole Abdomen', 'ultrasound-whole-abdomen-348', 'Ultrasound', 'Comprehensive Ultrasound Whole Abdomen test.', 'Ultrasound Whole Abdomen analysis.', 665, 865, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Lower Abdomen', 'ultrasound-lower-abdomen-349', 'Ultrasound', 'Comprehensive Ultrasound Lower Abdomen test.', 'Ultrasound Lower Abdomen analysis.', 455, 592, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Upper Abdomen', 'ultrasound-upper-abdomen-350', 'Ultrasound', 'Comprehensive Ultrasound Upper Abdomen test.', 'Ultrasound Upper Abdomen analysis.', 455, 592, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound KUB', 'ultrasound-kub-351', 'Ultrasound', 'Comprehensive Ultrasound KUB test.', 'Ultrasound KUB analysis.', 455, 592, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Pelvis (Female)', 'ultrasound-pelvis-female-352', 'Ultrasound', 'Comprehensive Ultrasound Pelvis (Female) test.', 'Ultrasound Pelvis (Female) analysis.', 455, 592, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Pelvis (Male)', 'ultrasound-pelvis-male-353', 'Ultrasound', 'Comprehensive Ultrasound Pelvis (Male) test.', 'Ultrasound Pelvis (Male) analysis.', 455, 592, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Transvaginal', 'ultrasound-transvaginal-354', 'Ultrasound', 'Comprehensive Ultrasound Transvaginal test.', 'Ultrasound Transvaginal analysis.', 599, 779, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Pregnancy (Obstetric)', 'ultrasound-pregnancy-obstetric-355', 'Ultrasound', 'Comprehensive Ultrasound Pregnancy (Obstetric) test.', 'Ultrasound Pregnancy (Obstetric) analysis.', 499, 649, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound NT Scan', 'ultrasound-nt-scan-356', 'Ultrasound', 'Comprehensive Ultrasound NT Scan test.', 'Ultrasound NT Scan analysis.', 899, 1169, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Anomaly Scan', 'ultrasound-anomaly-scan-357', 'Ultrasound', 'Comprehensive Ultrasound Anomaly Scan test.', 'Ultrasound Anomaly Scan analysis.', 999, 1299, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Thyroid', 'ultrasound-thyroid-358', 'Ultrasound', 'Comprehensive Ultrasound Thyroid test.', 'Ultrasound Thyroid analysis.', 399, 519, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Breast', 'ultrasound-breast-359', 'Ultrasound', 'Comprehensive Ultrasound Breast test.', 'Ultrasound Breast analysis.', 499, 649, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Scrotum', 'ultrasound-scrotum-360', 'Ultrasound', 'Comprehensive Ultrasound Scrotum test.', 'Ultrasound Scrotum analysis.', 399, 519, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Prostate', 'ultrasound-prostate-361', 'Ultrasound', 'Comprehensive Ultrasound Prostate test.', 'Ultrasound Prostate analysis.', 499, 649, 'Radiology/Imaging', 0, '12-72hr', true),
('Ultrasound Doppler Leg', 'ultrasound-doppler-leg-362', 'Ultrasound', 'Comprehensive Ultrasound Doppler Leg test.', 'Ultrasound Doppler Leg analysis.', 899, 1169, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan Head (Plain)', 'ct-scan-head-plain-363', 'CT Scan', 'Comprehensive CT Scan Head (Plain) test.', 'CT Scan Head (Plain) analysis.', 1800, 2340, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan Head (Contrast)', 'ct-scan-head-contrast-364', 'CT Scan', 'Comprehensive CT Scan Head (Contrast) test.', 'CT Scan Head (Contrast) analysis.', 2200, 2860, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan Chest (Plain)', 'ct-scan-chest-plain-365', 'CT Scan', 'Comprehensive CT Scan Chest (Plain) test.', 'CT Scan Chest (Plain) analysis.', 2300, 2990, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan Chest (Contrast)', 'ct-scan-chest-contrast-366', 'CT Scan', 'Comprehensive CT Scan Chest (Contrast) test.', 'CT Scan Chest (Contrast) analysis.', 2800, 3640, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan Whole Abdomen', 'ct-scan-whole-abdomen-367', 'CT Scan', 'Comprehensive CT Scan Whole Abdomen test.', 'CT Scan Whole Abdomen analysis.', 4000, 5200, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan Upper Abdomen', 'ct-scan-upper-abdomen-368', 'CT Scan', 'Comprehensive CT Scan Upper Abdomen test.', 'CT Scan Upper Abdomen analysis.', 2500, 3250, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan Lower Abdomen', 'ct-scan-lower-abdomen-369', 'CT Scan', 'Comprehensive CT Scan Lower Abdomen test.', 'CT Scan Lower Abdomen analysis.', 2500, 3250, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan KUB', 'ct-scan-kub-370', 'CT Scan', 'Comprehensive CT Scan KUB test.', 'CT Scan KUB analysis.', 2000, 2600, 'Radiology/Imaging', 0, '12-72hr', true),
('CT Scan Spine', 'ct-scan-spine-371', 'CT Scan', 'Comprehensive CT Scan Spine test.', 'CT Scan Spine analysis.', 2500, 3250, 'Radiology/Imaging', 0, '12-72hr', true),
('HRCT Chest (High Resolution)', 'hrct-chest-high-resolution-372', 'CT Scan', 'Comprehensive HRCT Chest (High Resolution) test.', 'HRCT Chest (High Resolution) analysis.', 2300, 2990, 'Radiology/Imaging', 0, '12-72hr', true),
('MRI Brain (Plain)', 'mri-brain-plain-373', 'MRI', 'Comprehensive MRI Brain (Plain) test.', 'MRI Brain (Plain) analysis.', 3500, 4550, 'Radiology/Imaging', 0, '24-48hr', true),
('MRI Brain (Contrast)', 'mri-brain-contrast-374', 'MRI', 'Comprehensive MRI Brain (Contrast) test.', 'MRI Brain (Contrast) analysis.', 4500, 5850, 'Radiology/Imaging', 0, '24-48hr', true),
('MRI Spine (Cervical)', 'mri-spine-cervical-375', 'MRI', 'Comprehensive MRI Spine (Cervical) test.', 'MRI Spine (Cervical) analysis.', 3500, 4550, 'Radiology/Imaging', 0, '24-48hr', true),
('MRI Spine (Thoracic)', 'mri-spine-thoracic-376', 'MRI', 'Comprehensive MRI Spine (Thoracic) test.', 'MRI Spine (Thoracic) analysis.', 3500, 4550, 'Radiology/Imaging', 0, '24-48hr', true),
('MRI Spine (Lumbar)', 'mri-spine-lumbar-377', 'MRI', 'Comprehensive MRI Spine (Lumbar) test.', 'MRI Spine (Lumbar) analysis.', 3500, 4550, 'Radiology/Imaging', 0, '24-48hr', true),
('MRI Knee Joint', 'mri-knee-joint-378', 'MRI', 'Comprehensive MRI Knee Joint test.', 'MRI Knee Joint analysis.', 3500, 4550, 'Radiology/Imaging', 0, '24-48hr', true),
('MRI Shoulder Joint', 'mri-shoulder-joint-379', 'MRI', 'Comprehensive MRI Shoulder Joint test.', 'MRI Shoulder Joint analysis.', 3500, 4550, 'Radiology/Imaging', 0, '24-48hr', true),
('MRI Abdomen', 'mri-abdomen-380', 'MRI', 'Comprehensive MRI Abdomen test.', 'MRI Abdomen analysis.', 4500, 5850, 'Radiology/Imaging', 0, '24-48hr', true),
('ECG (12-Lead)', 'ecg-12-lead-381', 'Cardiac & Vascular', 'Comprehensive ECG (12-Lead) test.', 'ECG (12-Lead) analysis.', 299, 389, 'Blood', 0, '30min', true),
('2D Echo with Doppler', '2d-echo-with-doppler-382', 'Cardiac & Vascular', 'Comprehensive 2D Echo with Doppler test.', '2D Echo with Doppler analysis.', 899, 1169, 'Blood', 0, '24hr', true),
('Stress ECG (TMT)', 'stress-ecg-tmt-383', 'Cardiac & Vascular', 'Comprehensive Stress ECG (TMT) test.', 'Stress ECG (TMT) analysis.', 899, 1169, 'Blood', 0, '24hr', true),
('Holter Monitoring (24hr)', 'holter-monitoring-24hr-384', 'Cardiac & Vascular', 'Comprehensive Holter Monitoring (24hr) test.', 'Holter Monitoring (24hr) analysis.', 1499, 1949, 'Blood', 0, '48hr', true),
('Ambulatory BP Monitoring', 'ambulatory-bp-monitoring-385', 'Cardiac & Vascular', 'Comprehensive Ambulatory BP Monitoring test.', 'Ambulatory BP Monitoring analysis.', 1499, 1949, 'Blood', 0, '48hr', true),
('Carotid Doppler', 'carotid-doppler-386', 'Cardiac & Vascular', 'Comprehensive Carotid Doppler test.', 'Carotid Doppler analysis.', 899, 1169, 'Blood', 0, '24hr', true),
('Peripheral Arterial Doppler', 'peripheral-arterial-doppler-387', 'Cardiac & Vascular', 'Comprehensive Peripheral Arterial Doppler test.', 'Peripheral Arterial Doppler analysis.', 899, 1169, 'Blood', 0, '24hr', true),
('Venous Doppler (DVT)', 'venous-doppler-dvt-388', 'Cardiac & Vascular', 'Comprehensive Venous Doppler (DVT) test.', 'Venous Doppler (DVT) analysis.', 899, 1169, 'Blood', 0, '24hr', true),
('Mammography (Screening)', 'mammography-screening-389', 'Radiology', 'Comprehensive Mammography (Screening) test.', 'Mammography (Screening) analysis.', 1499, 1949, 'Radiology/Imaging', 0, '24hr', true),
('Mammography (Diagnostic)', 'mammography-diagnostic-390', 'Radiology', 'Comprehensive Mammography (Diagnostic) test.', 'Mammography (Diagnostic) analysis.', 1799, 2339, 'Radiology/Imaging', 0, '24hr', true),
('DEXA Scan (Bone Density)', 'dexa-scan-bone-density-391', 'Radiology', 'Comprehensive DEXA Scan (Bone Density) test.', 'DEXA Scan (Bone Density) analysis.', 1299, 1689, 'Radiology/Imaging', 0, '24hr', true),
('Pulmonary Function Tests (PFT)', 'pulmonary-function-tests-pft-392', 'Radiology', 'Comprehensive Pulmonary Function Tests (PFT) test.', 'Pulmonary Function Tests (PFT) analysis.', 644, 837, 'Radiology/Imaging', 0, '12-72hr', true),
('Spirometry (PFT Basic)', 'spirometry-pft-basic-393', 'Pulmonary', 'Comprehensive Spirometry (PFT Basic) test.', 'Spirometry (PFT Basic) analysis.', 499, 649, 'Blood', 0, '12-72hr', true),
('DLCO (Lung Diffusion)', 'dlco-lung-diffusion-394', 'Pulmonary', 'Comprehensive DLCO (Lung Diffusion) test.', 'DLCO (Lung Diffusion) analysis.', 799, 1039, 'Blood', 0, '24hr', true),
('Lung Volumes (Body Plethysmography)', 'lung-volumes-body-plethysmography-395', 'Pulmonary', 'Comprehensive Lung Volumes (Body Plethysmography) test.', 'Lung Volumes (Body Plethysmography) analysis.', 899, 1169, 'Blood', 0, '24hr', true),
('FeNO (Fractional exhaled NO)', 'feno-fractional-exhaled-no-396', 'Pulmonary', 'Comprehensive FeNO (Fractional exhaled NO) test.', 'FeNO (Fractional exhaled NO) analysis.', 399, 519, 'Blood', 0, '2hr', true),
('Bronchial Challenge Test', 'bronchial-challenge-test-397', 'Pulmonary', 'Comprehensive Bronchial Challenge Test test.', 'Bronchial Challenge Test analysis.', 1299, 1689, 'Blood', 0, '48hr', true),
('EEG (Electroencephalogram)', 'eeg-electroencephalogram-398', 'Neurology', 'Comprehensive EEG (Electroencephalogram) test.', 'EEG (Electroencephalogram) analysis.', 999, 1299, 'Radiology/Imaging', 0, '24hr', true),
('Nerve Conduction Velocity (NCV)', 'nerve-conduction-velocity-ncv-399', 'Neurology', 'Comprehensive Nerve Conduction Velocity (NCV) test.', 'Nerve Conduction Velocity (NCV) analysis.', 1499, 1949, 'Radiology/Imaging', 0, '24hr', true),
('Electromyography (EMG)', 'electromyography-emg-400', 'Neurology', 'Comprehensive Electromyography (EMG) test.', 'Electromyography (EMG) analysis.', 1499, 1949, 'Radiology/Imaging', 0, '24hr', true),
('Visual Evoked Potential (VEP)', 'visual-evoked-potential-vep-401', 'Neurology', 'Comprehensive Visual Evoked Potential (VEP) test.', 'Visual Evoked Potential (VEP) analysis.', 899, 1169, 'Radiology/Imaging', 0, '24hr', true),
('Brainstem Auditory Evoked Response (BAER)', 'brainstem-auditory-evoked-response-baer-402', 'Neurology', 'Comprehensive Brainstem Auditory Evoked Response (BAER) test.', 'Brainstem Auditory Evoked Response (BAER) analysis.', 899, 1169, 'Radiology/Imaging', 0, '24hr', true),
('Somatosensory Evoked Potential (SSEP)', 'somatosensory-evoked-potential-ssep-403', 'Neurology', 'Comprehensive Somatosensory Evoked Potential (SSEP) test.', 'Somatosensory Evoked Potential (SSEP) analysis.', 899, 1169, 'Radiology/Imaging', 0, '24hr', true),
('Polysomnography (Sleep Study)', 'polysomnography-sleep-study-404', 'Neurology', 'Comprehensive Polysomnography (Sleep Study) test.', 'Polysomnography (Sleep Study) analysis.', 4999, 6499, 'Radiology/Imaging', 0, '96hr', true),
('Quantitative Sensory Testing', 'quantitative-sensory-testing-405', 'Neurology', 'Comprehensive Quantitative Sensory Testing test.', 'Quantitative Sensory Testing analysis.', 1999, 2599, 'Radiology/Imaging', 0, '48hr', true),
('Upper GI Endoscopy', 'upper-gi-endoscopy-406', 'Endoscopy', 'Comprehensive Upper GI Endoscopy test.', 'Upper GI Endoscopy analysis.', 2499, 3249, 'Radiology/Imaging', 0, '24hr', true),
('Colonoscopy', 'colonoscopy-407', 'Endoscopy', 'Comprehensive Colonoscopy test.', 'Colonoscopy analysis.', 2999, 3899, 'Radiology/Imaging', 0, '24hr', true),
('Sigmoidoscopy', 'sigmoidoscopy-408', 'Endoscopy', 'Comprehensive Sigmoidoscopy test.', 'Sigmoidoscopy analysis.', 1499, 1949, 'Radiology/Imaging', 0, '24hr', true),
('Capsule Endoscopy', 'capsule-endoscopy-409', 'Endoscopy', 'Comprehensive Capsule Endoscopy test.', 'Capsule Endoscopy analysis.', 9999, 12999, 'Radiology/Imaging', 0, '72hr', true),
('ERCP', 'ercp-410', 'Endoscopy', 'Comprehensive ERCP test.', 'ERCP analysis.', 7999, 10399, 'Radiology/Imaging', 0, '48hr', true),
('Endoscopic Ultrasound', 'endoscopic-ultrasound-411', 'Endoscopy', 'Comprehensive Endoscopic Ultrasound test.', 'Endoscopic Ultrasound analysis.', 5999, 7799, 'Radiology/Imaging', 0, '48hr', true),
('FNAC (Fine Needle Aspiration)', 'fnac-fine-needle-aspiration-412', 'Biopsy', 'Comprehensive FNAC (Fine Needle Aspiration) test.', 'FNAC (Fine Needle Aspiration) analysis.', 999, 1299, 'Tissue', 0, '24hr', true),
('Core Needle Biopsy', 'core-needle-biopsy-413', 'Biopsy', 'Comprehensive Core Needle Biopsy test.', 'Core Needle Biopsy analysis.', 1499, 1949, 'Tissue', 0, '48hr', true),
('Punch Biopsy (Skin)', 'punch-biopsy-skin-414', 'Biopsy', 'Comprehensive Punch Biopsy (Skin) test.', 'Punch Biopsy (Skin) analysis.', 799, 1039, 'Tissue', 0, '48hr', true),
('Endometrial Biopsy', 'endometrial-biopsy-415', 'Biopsy', 'Comprehensive Endometrial Biopsy test.', 'Endometrial Biopsy analysis.', 1299, 1689, 'Tissue', 0, '48hr', true),
('Liver Biopsy', 'liver-biopsy-416', 'Biopsy', 'Comprehensive Liver Biopsy test.', 'Liver Biopsy analysis.', 1999, 2599, 'Tissue', 0, '72hr', true),
('Kidney Biopsy', 'kidney-biopsy-417', 'Biopsy', 'Comprehensive Kidney Biopsy test.', 'Kidney Biopsy analysis.', 1999, 2599, 'Tissue', 0, '72hr', true),
('Bone Marrow Biopsy', 'bone-marrow-biopsy-418', 'Biopsy', 'Comprehensive Bone Marrow Biopsy test.', 'Bone Marrow Biopsy analysis.', 2499, 3249, 'Tissue', 0, '72hr', true),
('Muscle Biopsy', 'muscle-biopsy-419', 'Biopsy', 'Comprehensive Muscle Biopsy test.', 'Muscle Biopsy analysis.', 1999, 2599, 'Tissue', 0, '72hr', true),
('CSF Analysis (Complete)', 'csf-analysis-complete-420', 'Fluid Analysis', 'Comprehensive CSF Analysis (Complete) test.', 'CSF Analysis (Complete) analysis.', 999, 1299, 'Fluid', 0, '24hr', true),
('Pleural Fluid Analysis', 'pleural-fluid-analysis-421', 'Fluid Analysis', 'Comprehensive Pleural Fluid Analysis test.', 'Pleural Fluid Analysis analysis.', 599, 779, 'Fluid', 0, '24hr', true),
('Ascitic Fluid Analysis', 'ascitic-fluid-analysis-422', 'Fluid Analysis', 'Comprehensive Ascitic Fluid Analysis test.', 'Ascitic Fluid Analysis analysis.', 599, 779, 'Fluid', 0, '24hr', true),
('Pericardial Fluid Analysis', 'pericardial-fluid-analysis-423', 'Fluid Analysis', 'Comprehensive Pericardial Fluid Analysis test.', 'Pericardial Fluid Analysis analysis.', 599, 779, 'Fluid', 0, '24hr', true),
('Synovial Fluid Analysis', 'synovial-fluid-analysis-424', 'Fluid Analysis', 'Comprehensive Synovial Fluid Analysis test.', 'Synovial Fluid Analysis analysis.', 599, 779, 'Fluid', 0, '24hr', true),
('Semen Analysis (Complete)', 'semen-analysis-complete-425', 'Fluid Analysis', 'Comprehensive Semen Analysis (Complete) test.', 'Semen Analysis (Complete) analysis.', 499, 649, 'Fluid', 0, '24hr', true),
('PCR (Generic)', 'pcr-generic-426', 'Genetic', 'Comprehensive PCR (Generic) test.', 'PCR (Generic) analysis.', 999, 1299, 'Blood', 0, '48hr', true),
('RT-PCR (Quantitative)', 'rt-pcr-quantitative-427', 'Genetic', 'Comprehensive RT-PCR (Quantitative) test.', 'RT-PCR (Quantitative) analysis.', 1499, 1949, 'Blood', 0, '48hr', true),
('DNA Sequencing', 'dna-sequencing-428', 'Genetic', 'Comprehensive DNA Sequencing test.', 'DNA Sequencing analysis.', 2999, 3899, 'Blood', 0, '96hr', true),
('Genetic Mutation Analysis', 'genetic-mutation-analysis-429', 'Genetic', 'Comprehensive Genetic Mutation Analysis test.', 'Genetic Mutation Analysis analysis.', 3999, 5199, 'Blood', 0, '120hr', true),
('Karyotyping', 'karyotyping-430', 'Genetic', 'Comprehensive Karyotyping test.', 'Karyotyping analysis.', 1999, 2599, 'Blood', 0, '120hr', true),
('FISH (Fluorescence In Situ Hybridization)', 'fish-fluorescence-in-situ-hybridization-431', 'Genetic', 'Comprehensive FISH (Fluorescence In Situ Hybridization) test.', 'FISH (Fluorescence In Situ Hybridization) analysis.', 4999, 6499, 'Blood', 0, '96hr', true),
('Microarray (CMA)', 'microarray-cma-432', 'Genetic', 'Comprehensive Microarray (CMA) test.', 'Microarray (CMA) analysis.', 9999, 12999, 'Blood', 0, '168hr', true),
('Newborn Screening (NBS)', 'newborn-screening-nbs-433', 'Genetic', 'Comprehensive Newborn Screening (NBS) test.', 'Newborn Screening (NBS) analysis.', 1499, 1949, 'Blood', 0, '72hr', true),
('Carrier Screening (Thalassemia)', 'carrier-screening-thalassemia-434', 'Genetic', 'Comprehensive Carrier Screening (Thalassemia) test.', 'Carrier Screening (Thalassemia) analysis.', 1999, 2599, 'Blood', 0, '96hr', true),
('Prenatal Screening (Triple/Quad Test)', 'prenatal-screening-triple-quad-test-435', 'Genetic', 'Comprehensive Prenatal Screening (Triple/Quad Test) test.', 'Prenatal Screening (Triple/Quad Test) analysis.', 1499, 1949, 'Blood', 0, '72hr', true),
('Therapeutic Drug Monitoring (TDM)', 'therapeutic-drug-monitoring-tdm-436', 'Drug Monitoring', 'Comprehensive Therapeutic Drug Monitoring (TDM) test.', 'Therapeutic Drug Monitoring (TDM) analysis.', 999, 1299, 'Blood', 0, '24hr', true),
('Digoxin Level', 'digoxin-level-437', 'Drug Monitoring', 'Comprehensive Digoxin Level test.', 'Digoxin Level analysis.', 499, 649, 'Blood', 0, '24hr', true),
('Phenytoin Level', 'phenytoin-level-438', 'Drug Monitoring', 'Comprehensive Phenytoin Level test.', 'Phenytoin Level analysis.', 499, 649, 'Blood', 0, '24hr', true),
('Carbamazepine Level', 'carbamazepine-level-439', 'Drug Monitoring', 'Comprehensive Carbamazepine Level test.', 'Carbamazepine Level analysis.', 499, 649, 'Blood', 0, '24hr', true),
('Valproate Level', 'valproate-level-440', 'Drug Monitoring', 'Comprehensive Valproate Level test.', 'Valproate Level analysis.', 499, 649, 'Blood', 0, '24hr', true),
('Lithium Level', 'lithium-level-441', 'Drug Monitoring', 'Comprehensive Lithium Level test.', 'Lithium Level analysis.', 499, 649, 'Blood', 0, '24hr', true),
('Cyclosporine Level', 'cyclosporine-level-442', 'Drug Monitoring', 'Comprehensive Cyclosporine Level test.', 'Cyclosporine Level analysis.', 799, 1039, 'Blood', 0, '24hr', true),
('Basic Health Checkup', 'basic-health-checkup-443', 'Basic Health', 'Comprehensive Basic Health Checkup test.', 'Basic Health Checkup analysis.', 999, 1299, 'Blood', 1, '48hr', true),
('Comprehensive Health Checkup', 'comprehensive-health-checkup-444', 'Basic Health', 'Comprehensive Comprehensive Health Checkup test.', 'Comprehensive Health Checkup analysis.', 1899, 2469, 'Blood', 1, '48hr', true),
('Advanced Health Checkup', 'advanced-health-checkup-445', 'Basic Health', 'Comprehensive Advanced Health Checkup test.', 'Advanced Health Checkup analysis.', 2999, 3899, 'Blood', 1, '48hr', true),
('Executive Health Checkup', 'executive-health-checkup-446', 'Basic Health', 'Comprehensive Executive Health Checkup test.', 'Executive Health Checkup analysis.', 4999, 6499, 'Blood', 1, '72hr', true),
('Premium Health Checkup', 'premium-health-checkup-447', 'Basic Health', 'Comprehensive Premium Health Checkup test.', 'Premium Health Checkup analysis.', 7999, 10399, 'Blood', 1, '96hr', true),
('Women''s Health Checkup', 'women-s-health-checkup-448', 'Basic Health', 'Comprehensive Women''s Health Checkup test.', 'Women''s Health Checkup analysis.', 2499, 3249, 'Blood', 1, '48hr', true),
('Men''s Health Checkup', 'men-s-health-checkup-449', 'Basic Health', 'Comprehensive Men''s Health Checkup test.', 'Men''s Health Checkup analysis.', 2499, 3249, 'Blood', 1, '48hr', true),
('Senior Citizen Checkup', 'senior-citizen-checkup-450', 'Basic Health', 'Comprehensive Senior Citizen Checkup test.', 'Senior Citizen Checkup analysis.', 3499, 4549, 'Blood', 1, '48hr', true),
('Diabetes Care Package', 'diabetes-care-package-451', 'Disease Specific', 'Comprehensive Diabetes Care Package test.', 'Diabetes Care Package analysis.', 1499, 1949, 'Blood', 1, '48hr', true),
('Cardiac Care Package', 'cardiac-care-package-452', 'Disease Specific', 'Comprehensive Cardiac Care Package test.', 'Cardiac Care Package analysis.', 1499, 1949, 'Blood', 1, '48hr', true),
('Liver Care Package', 'liver-care-package-453', 'Disease Specific', 'Comprehensive Liver Care Package test.', 'Liver Care Package analysis.', 1299, 1689, 'Blood', 1, '48hr', true),
('Kidney Care Package', 'kidney-care-package-454', 'Disease Specific', 'Comprehensive Kidney Care Package test.', 'Kidney Care Package analysis.', 1299, 1689, 'Blood', 1, '48hr', true),
('Thyroid Care Package', 'thyroid-care-package-455', 'Disease Specific', 'Comprehensive Thyroid Care Package test.', 'Thyroid Care Package analysis.', 999, 1299, 'Blood', 0, '48hr', true),
('Arthritis Care Package', 'arthritis-care-package-456', 'Disease Specific', 'Comprehensive Arthritis Care Package test.', 'Arthritis Care Package analysis.', 1499, 1949, 'Blood', 1, '72hr', true),
('Allergy Testing Package', 'allergy-testing-package-457', 'Disease Specific', 'Comprehensive Allergy Testing Package test.', 'Allergy Testing Package analysis.', 2499, 3249, 'Blood', 0, '96hr', true),
('Vitamin & Nutrition Package', 'vitamin-nutrition-package-458', 'Disease Specific', 'Comprehensive Vitamin & Nutrition Package test.', 'Vitamin & Nutrition Package analysis.', 1299, 1689, 'Blood', 1, '48hr', true),
('Iron Deficiency Package', 'iron-deficiency-package-459', 'Disease Specific', 'Comprehensive Iron Deficiency Package test.', 'Iron Deficiency Package analysis.', 899, 1169, 'Blood', 1, '48hr', true),
('PCOS/Hormone Package', 'pcos-hormone-package-460', 'Disease Specific', 'Comprehensive PCOS/Hormone Package test.', 'PCOS/Hormone Package analysis.', 1999, 2599, 'Blood', 1, '48hr', true),
('Fertility Assessment (Female)', 'fertility-assessment-female-461', 'Disease Specific', 'Comprehensive Fertility Assessment (Female) test.', 'Fertility Assessment (Female) analysis.', 3499, 4549, 'Blood', 0, '72hr', true),
('Fertility Assessment (Male)', 'fertility-assessment-male-462', 'Disease Specific', 'Comprehensive Fertility Assessment (Male) test.', 'Fertility Assessment (Male) analysis.', 2499, 3249, 'Blood', 0, '48hr', true),
('Fever Package (Basic)', 'fever-package-basic-463', 'Fever', 'Comprehensive Fever Package (Basic) test.', 'Fever Package (Basic) analysis.', 999, 1299, 'Blood', 0, '48hr', true),
('Fever Package (Advanced)', 'fever-package-advanced-464', 'Fever', 'Comprehensive Fever Package (Advanced) test.', 'Fever Package (Advanced) analysis.', 1999, 2599, 'Blood', 0, '72hr', true),
('Dengue Package', 'dengue-package-465', 'Fever', 'Comprehensive Dengue Package test.', 'Dengue Package analysis.', 999, 1299, 'Blood', 0, '48hr', true),
('Typhoid Package', 'typhoid-package-466', 'Fever', 'Comprehensive Typhoid Package test.', 'Typhoid Package analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('Malaria Package', 'malaria-package-467', 'Fever', 'Comprehensive Malaria Package test.', 'Malaria Package analysis.', 699, 909, 'Blood', 0, '48hr', true),
('Respiratory Infection Package', 'respiratory-infection-package-468', 'Fever', 'Comprehensive Respiratory Infection Package test.', 'Respiratory Infection Package analysis.', 1499, 1949, 'Blood', 0, '72hr', true),
('Pre-Employment Checkup', 'pre-employment-checkup-469', 'Insurance', 'Comprehensive Pre-Employment Checkup test.', 'Pre-Employment Checkup analysis.', 999, 1299, 'Blood', 1, '48hr', true),
('Insurance Medical Checkup', 'insurance-medical-checkup-470', 'Insurance', 'Comprehensive Insurance Medical Checkup test.', 'Insurance Medical Checkup analysis.', 1499, 1949, 'Blood', 1, '48hr', true),
('Visa Medical Checkup', 'visa-medical-checkup-471', 'Insurance', 'Comprehensive Visa Medical Checkup test.', 'Visa Medical Checkup analysis.', 1999, 2599, 'Blood', 1, '48hr', true),
('School/College Checkup', 'school-college-checkup-472', 'Insurance', 'Comprehensive School/College Checkup test.', 'School/College Checkup analysis.', 799, 1039, 'Blood', 1, '48hr', true),
('Beta-hCG (Pregnancy)', 'beta-hcg-pregnancy-473', 'Pregnancy', 'Comprehensive Beta-hCG (Pregnancy) test.', 'Beta-hCG (Pregnancy) analysis.', 349, 454, 'Blood', 0, '4hr', true),
('Double Marker Test', 'double-marker-test-474', 'Pregnancy', 'Comprehensive Double Marker Test test.', 'Double Marker Test analysis.', 1499, 1949, 'Blood', 0, '72hr', true),
('Triple Marker Test', 'triple-marker-test-475', 'Pregnancy', 'Comprehensive Triple Marker Test test.', 'Triple Marker Test analysis.', 1799, 2339, 'Blood', 0, '72hr', true),
('Quadruple Marker Test', 'quadruple-marker-test-476', 'Pregnancy', 'Comprehensive Quadruple Marker Test test.', 'Quadruple Marker Test analysis.', 1999, 2599, 'Blood', 0, '72hr', true),
('NIPT (Non-Invasive Prenatal Test)', 'nipt-non-invasive-prenatal-test-477', 'Pregnancy', 'Comprehensive NIPT (Non-Invasive Prenatal Test) test.', 'NIPT (Non-Invasive Prenatal Test) analysis.', 9999, 12999, 'Blood', 0, '120hr', true),
('Amniocentesis', 'amniocentesis-478', 'Pregnancy', 'Comprehensive Amniocentesis test.', 'Amniocentesis analysis.', 7999, 10399, 'Blood', 0, '168hr', true),
('CVS (Chorionic Villus Sampling)', 'cvs-chorionic-villus-sampling-479', 'Pregnancy', 'Comprehensive CVS (Chorionic Villus Sampling) test.', 'CVS (Chorionic Villus Sampling) analysis.', 7999, 10399, 'Blood', 0, '168hr', true),
('Progesterone (Fertility)', 'progesterone-fertility-480', 'Pregnancy', 'Comprehensive Progesterone (Fertility) test.', 'Progesterone (Fertility) analysis.', 349, 454, 'Blood', 0, '24hr', true),
('AMH (Fertility)', 'amh-fertility-481', 'Pregnancy', 'Comprehensive AMH (Fertility) test.', 'AMH (Fertility) analysis.', 899, 1169, 'Blood', 0, '48hr', true),
('Ovulation Predictor Kit', 'ovulation-predictor-kit-482', 'Pregnancy', 'Comprehensive Ovulation Predictor Kit test.', 'Ovulation Predictor Kit analysis.', 199, 259, 'Blood', 0, '2hr', true),
('Fundus Photography', 'fundus-photography-483', 'Ophthalmology', 'Comprehensive Fundus Photography test.', 'Fundus Photography analysis.', 399, 519, 'Radiology/Imaging', 0, '2hr', true),
('OCT (Optical Coherence Tomography)', 'oct-optical-coherence-tomography-484', 'Ophthalmology', 'Comprehensive OCT (Optical Coherence Tomography) test.', 'OCT (Optical Coherence Tomography) analysis.', 1499, 1949, 'Radiology/Imaging', 0, '2hr', true),
('Visual Field Test (Perimetry)', 'visual-field-test-perimetry-485', 'Ophthalmology', 'Comprehensive Visual Field Test (Perimetry) test.', 'Visual Field Test (Perimetry) analysis.', 899, 1169, 'Radiology/Imaging', 0, '2hr', true),
('Corneal Topography', 'corneal-topography-486', 'Ophthalmology', 'Comprehensive Corneal Topography test.', 'Corneal Topography analysis.', 799, 1039, 'Radiology/Imaging', 0, '2hr', true),
('Specular Microscopy', 'specular-microscopy-487', 'Ophthalmology', 'Comprehensive Specular Microscopy test.', 'Specular Microscopy analysis.', 599, 779, 'Radiology/Imaging', 0, '2hr', true),
('Dental X-Ray (OPG)', 'dental-x-ray-opg-488', 'Dental', 'Comprehensive Dental X-Ray (OPG) test.', 'Dental X-Ray (OPG) analysis.', 499, 649, 'Radiology/Imaging', 0, '2hr', true),
('Dental X-Ray (IOPA)', 'dental-x-ray-iopa-489', 'Dental', 'Comprehensive Dental X-Ray (IOPA) test.', 'Dental X-Ray (IOPA) analysis.', 199, 259, 'Radiology/Imaging', 0, '2hr', true),
('CBCT Dental', 'cbct-dental-490', 'Dental', 'Comprehensive CBCT Dental test.', 'CBCT Dental analysis.', 1499, 1949, 'Radiology/Imaging', 0, '24hr', true),
('Dental Panoramic X-Ray', 'dental-panoramic-x-ray-491', 'Dental', 'Comprehensive Dental Panoramic X-Ray test.', 'Dental Panoramic X-Ray analysis.', 599, 779, 'Radiology/Imaging', 0, '2hr', true),
('Cephalometric X-Ray', 'cephalometric-x-ray-492', 'Dental', 'Comprehensive Cephalometric X-Ray test.', 'Cephalometric X-Ray analysis.', 699, 909, 'Radiology/Imaging', 0, '2hr', true),
('Pure Tone Audiometry', 'pure-tone-audiometry-493', 'Audiology', 'Comprehensive Pure Tone Audiometry test.', 'Pure Tone Audiometry analysis.', 399, 519, 'Radiology/Imaging', 0, '2hr', true),
('Impedance Audiometry', 'impedance-audiometry-494', 'Audiology', 'Comprehensive Impedance Audiometry test.', 'Impedance Audiometry analysis.', 399, 519, 'Radiology/Imaging', 0, '2hr', true),
('OAE (Otoacoustic Emissions)', 'oae-otoacoustic-emissions-495', 'Audiology', 'Comprehensive OAE (Otoacoustic Emissions) test.', 'OAE (Otoacoustic Emissions) analysis.', 499, 649, 'Radiology/Imaging', 0, '2hr', true),
('BERA (Brainstem Evoked Response Audiometry)', 'bera-brainstem-evoked-response-audiometry-496', 'Audiology', 'Comprehensive BERA (Brainstem Evoked Response Audiometry) test.', 'BERA (Brainstem Evoked Response Audiometry) analysis.', 899, 1169, 'Radiology/Imaging', 0, '2hr', true),
('Hearing Aid Trial & Fitting', 'hearing-aid-trial-fitting-497', 'Audiology', 'Comprehensive Hearing Aid Trial & Fitting test.', 'Hearing Aid Trial & Fitting analysis.', 999, 1299, 'Radiology/Imaging', 0, '2hr', true),
('Skin Prick Test (Allergy)', 'skin-prick-test-allergy-498', 'Miscellaneous', 'Comprehensive Skin Prick Test (Allergy) test.', 'Skin Prick Test (Allergy) analysis.', 999, 1299, 'Blood', 0, '2hr', true),
('Patch Test (Contact Dermatitis)', 'patch-test-contact-dermatitis-499', 'Miscellaneous', 'Comprehensive Patch Test (Contact Dermatitis) test.', 'Patch Test (Contact Dermatitis) analysis.', 1499, 1949, 'Blood', 0, '96hr', true),
('Sweat Chloride Test (Cystic Fibrosis)', 'sweat-chloride-test-cystic-fibrosis-500', 'Miscellaneous', 'Comprehensive Sweat Chloride Test (Cystic Fibrosis) test.', 'Sweat Chloride Test (Cystic Fibrosis) analysis.', 899, 1169, 'Blood', 0, '24hr', true),
('H.Pylori Breath Test', 'h-pylori-breath-test-501', 'Miscellaneous', 'Comprehensive H.Pylori Breath Test test.', 'H.Pylori Breath Test analysis.', 899, 1169, 'Blood', 0, '2hr', true),
('Lactose Tolerance Test', 'lactose-tolerance-test-502', 'Miscellaneous', 'Comprehensive Lactose Tolerance Test test.', 'Lactose Tolerance Test analysis.', 499, 649, 'Blood', 1, '4hr', true);
