ALTER TABLE audit_logs
    ADD COLUMN IF NOT EXISTS user_email VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS user_role VARCHAR(30) NULL,
    ADD COLUMN IF NOT EXISTS entity_type VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS old_value TEXT NULL,
    ADD COLUMN IF NOT EXISTS new_value TEXT NULL,
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(50) NULL;
