import { 
  Droplets, Activity, Heart, Brain, FlaskConical, Leaf, Bone, Shield, Zap, Baby, Eye, Wind, Star
} from 'lucide-react';

export const DOCTOR_SCREENS = [
  { label: 'Diabetes', slug: 'diabetes', bg: 'from-blue-50 to-cyan-50', icon: Droplets, iconColor: '#0EA5E9', desc: 'Blood Sugar & HbA1c panel' },
  { label: 'Full Body', slug: 'full-body-checkup', bg: 'from-emerald-50 to-teal-50', icon: Activity, iconColor: '#059669', desc: 'Complete health screen, 65+ params' },
  { label: 'Heart',     slug: 'heart', bg: 'from-red-50 to-pink-50', icon: Heart, iconColor: '#E11D48', desc: 'Cardiac risk & lipid profile' },
  { label: 'Thyroid',   slug: 'thyroid', bg: 'from-purple-50 to-violet-50', icon: Brain, iconColor: '#7C3AED', desc: 'T3, T4, TSH comprehensive' },
  { label: 'Kidney',    slug: 'kidney', bg: 'from-yellow-50 to-amber-50', icon: FlaskConical, iconColor: '#D97706', desc: 'KFT with creatinine & urea' },
  { label: 'Liver',     slug: 'liver', bg: 'from-orange-50 to-amber-50', icon: Leaf, iconColor: '#EA580C', desc: 'LFT with bilirubin panel' },
  { label: 'Bone',      slug: 'bone-health', bg: 'from-lime-50 to-green-50', icon: Bone, iconColor: '#65A30D', desc: 'Vitamin D3, calcium, phosphate' },
  { label: 'Immunity',  slug: 'immunity', bg: 'from-sky-50 to-blue-50', icon: Shield, iconColor: '#0369A1', desc: 'CBC with immune markers' },
  { label: 'Nutrition', slug: 'nutrition', bg: 'from-teal-50 to-cyan-50', icon: Zap, iconColor: '#0891B2', desc: 'Vitamins B12, D & iron panel' },
  { label: 'Fever',     slug: 'fever', bg: 'from-red-50 to-orange-50', icon: Activity, iconColor: '#EF4444', desc: 'Viral, malaria & dengue panel' },
  { label: 'Pregnancy', slug: 'pregnancy', bg: 'from-pink-50 to-rose-50', icon: Baby, iconColor: '#DB2777', desc: 'Antenatal care screen panel' },
  { label: 'Eye Care',  slug: 'eye-care', bg: 'from-slate-50 to-gray-50', icon: Eye, iconColor: '#475569', desc: 'Diabetic retinopathy markers' },
  { label: 'Lungs',     slug: 'lungs', bg: 'from-indigo-50 to-sky-50', icon: Wind, iconColor: '#4F46E5', desc: 'PFT & respiratory markers' },
  { label: 'Cancer',    slug: 'cancer', bg: 'from-rose-50 to-red-50', icon: Shield, iconColor: '#BE123C', desc: 'Tumor markers & screening' },
  { label: 'Digestion', slug: 'digestion', bg: 'from-orange-50 to-yellow-50', icon: Leaf, iconColor: '#C2410C', desc: 'Gut health & stomach screen' },
  { label: 'Allergy',   slug: 'allergy', bg: 'from-green-50 to-emerald-50', icon: Wind, iconColor: '#10B981', desc: 'IgE & allergy panel' },
  { label: 'Stress',    slug: 'stress', bg: 'from-violet-50 to-indigo-50', icon: Brain, iconColor: '#6D28D9', desc: 'Cortisol & stress markers' },
  { label: 'Skin/Hair', slug: 'skin-hair', bg: 'from-amber-50 to-yellow-50', icon: Star, iconColor: '#D97706', desc: 'Biotin & skin vitality' },
  { label: 'Hormones',  slug: 'hormones', bg: 'from-fuchsia-50 to-purple-50', icon: FlaskConical, iconColor: '#A21CAF', desc: 'PCOS & endocrine screen' },
  { label: 'Joints',    slug: 'joints', bg: 'from-stone-50 to-slate-50', icon: Bone, iconColor: '#57534E', desc: 'RA factor & arthritis screen' },
  { label: 'Anemia',    slug: 'anemia', bg: 'from-red-50 to-rose-50', icon: Droplets, iconColor: '#991B1B', desc: 'Iron, ferritin & blood count' },
  { label: 'Brain',     slug: 'brain', bg: 'from-blue-50 to-indigo-50', icon: Brain, iconColor: '#1E40AF', desc: 'Neuro markers & memory' },
  { label: 'Weight',    slug: 'weight', bg: 'from-cyan-50 to-blue-50', icon: Activity, iconColor: '#0891B2', desc: 'Metabolic rate & BMI profile' },
  { label: 'Senior',    slug: 'senior-citizen', bg: 'from-slate-50 to-blue-50', icon: Heart, iconColor: '#334155', desc: 'Geriatric health panel' },
  { label: 'ChildCare', slug: 'pediatric', bg: 'from-yellow-50 to-orange-50', icon: Baby, iconColor: '#F59E0B', desc: 'Growth & pediatric screen' },
  { label: 'STD',       slug: 'sexual-health', bg: 'from-red-50 to-pink-50', icon: Shield, iconColor: '#E11D48', desc: 'Sexual wellness screen' },
  { label: 'Fitness',   slug: 'fitness', bg: 'from-emerald-50 to-green-50', icon: Zap, iconColor: '#059669', desc: 'Pre-workout health screen' },
  { label: 'Vitality',  slug: 'vitality', bg: 'from-orange-50 to-red-50', icon: Star, iconColor: '#C2410C', desc: 'Energy & stamina markers' },
  { label: 'Healthy',   slug: 'wellness', bg: 'from-teal-50 to-emerald-50', icon: Leaf, iconColor: '#0F766E', desc: 'Preventative wellness check' },
];

export const VITAL_ORGANS = [
  { label: 'Thyroid',       slug: 'thyroid',            icon: Brain,        iconColor: '#7C3AED', bg: 'from-purple-50 to-violet-50', desc: 'TSH, T3, T4 levels' },
  { label: 'Heart',         slug: 'heart',              icon: Heart,        iconColor: '#E11D48', bg: 'from-red-50 to-pink-50',     desc: 'Lipids & cardiac risk' },
  { label: 'Kidney',        slug: 'kidney',             icon: Activity,     iconColor: '#D97706', bg: 'from-yellow-50 to-amber-50', desc: 'KFT & creatinine' },
  { label: 'Liver',         slug: 'liver',              icon: Droplets,     iconColor: '#EA580C', bg: 'from-orange-50 to-amber-50', desc: 'LFT & bilirubin panel' },
  { label: 'Bone Health',   slug: 'bone-health',        icon: Bone,         iconColor: '#65A30D', bg: 'from-lime-50 to-green-50',   desc: 'Vitamin D & Calcium' },
  { label: 'Lungs',         slug: 'lungs',              icon: Wind,         iconColor: '#4F46E5', bg: 'from-indigo-50 to-sky-50',   desc: 'Respiratory efficiency' },
  { label: 'Full Body',     slug: 'full-body-checkup',  icon: Activity,     iconColor: '#059669', bg: 'from-emerald-50 to-teal-50', desc: 'Complete health check' },
  { label: 'Brain',         slug: 'brain',              icon: Brain,        iconColor: '#1E40AF', bg: 'from-blue-50 to-indigo-50',  desc: 'Neuro & cognitive health' },
  { label: 'Eye',           slug: 'ophthalmology',      icon: Eye,          iconColor: '#0891B2', bg: 'from-cyan-50 to-blue-50',    desc: 'Vision & retinal health' },
  { label: 'Skin',          slug: 'dermatology',        icon: Star,         iconColor: '#EA580C', bg: 'from-orange-50 to-amber-50', desc: 'Dermatological health' },
  { label: 'Joint Pain',    slug: 'joint',              icon: Bone,         iconColor: '#57534E', bg: 'from-stone-50 to-slate-50',  desc: 'Arthritis & joint screen' },
  { label: 'Diabetes',      slug: 'diabetes',           icon: Droplets,     iconColor: '#0EA5E9', bg: 'from-blue-50 to-cyan-50',    desc: 'Blood sugar management' },
];

export const POPULAR_CATEGORIES = [
  { label: 'Full Body Checkup', slug: 'full-body-checkup', icon: Activity,      iconColor: '#059669', bg: 'from-emerald-50 to-teal-50',   desc: '65+ parameters health screen' },
  { label: 'Diabetes',          slug: 'diabetes',           icon: Droplets,      iconColor: '#0EA5E9', bg: 'from-blue-50 to-cyan-50',      desc: 'HbA1c & sugar monitoring' },
  { label: 'Heart',             slug: 'heart',              icon: Heart,         iconColor: '#E11D48', bg: 'from-red-50 to-pink-50',       desc: 'Cardiac markers & Lipid profile' },
  { label: 'Thyroid',           slug: 'thyroid',            icon: Brain,         iconColor: '#7C3AED', bg: 'from-purple-50 to-violet-50',  desc: 'TSH, T3 & T4 comprehensive' },
  { label: 'Kidney',            slug: 'kidney',             icon: FlaskConical,  iconColor: '#D97706', bg: 'from-yellow-50 to-amber-50',  desc: 'Creatinine, Urea & KFT' },
  { label: 'Liver',             slug: 'liver',              icon: Droplets,      iconColor: '#EA580C', bg: 'from-orange-50 to-amber-50',  desc: 'LFT, Bilirubin & Enzyme panel' },
  { label: "Women's Health",    slug: 'womens-health',      icon: Star,          iconColor: '#DB2777', bg: 'from-pink-50 to-rose-50',      desc: 'PCOS & general screenings' },
  { label: 'Senior Citizen',    slug: 'senior-citizen',     icon: Heart,         iconColor: '#334155', bg: 'from-slate-50 to-blue-50',     desc: 'Geriatric health & vital scan' },
  { label: 'Vitamin',           slug: 'vitamin',            icon: Zap,           iconColor: '#0891B2', bg: 'from-teal-50 to-cyan-50',      desc: 'Vitamin D, B12 & deficiencies' },
  { label: 'Cancer Markers',    slug: 'cancer-markers',     icon: Shield,        iconColor: '#BE123C', bg: 'from-rose-50 to-red-50',       desc: 'PSA, CA-125 & tumor markers' },
  { label: 'Allergy',           slug: 'allergy',            icon: Wind,          iconColor: '#10B981', bg: 'from-green-50 to-emerald-50', desc: 'IgE & common allergen panel' },
  { label: 'Hormones',          slug: 'hormones',           icon: FlaskConical,  iconColor: '#A21CAF', bg: 'from-fuchsia-50 to-purple-50', desc: 'Steroid & reproductive markers' },
  { label: 'Bone Health',       slug: 'bone-health',        icon: Bone,          iconColor: '#65A30D', bg: 'from-lime-50 to-green-50',     desc: 'Calcium & bone density check' },
  { label: 'Urine',             slug: 'urine',              icon: Droplets,      iconColor: '#0369A1', bg: 'from-sky-50 to-blue-50',       desc: 'Routine & microscopic analysis' },
  { label: 'Iron Deficiency',   slug: 'iron-deficiency',    icon: Activity,      iconColor: '#991B1B', bg: 'from-red-50 to-rose-50',       desc: 'Ferritin & iron studies' },
  { label: 'CBC',                slug: 'cbc',                icon: Activity,      iconColor: '#B91C1C', bg: 'from-red-50 to-orange-50',     desc: 'Complete blood count analysis' },
  { label: 'Pregnancy',         slug: 'pregnancy',          icon: Baby,          iconColor: '#BE185D', bg: 'from-pink-100 to-rose-50',    desc: 'Antenatal care & HCG screen' },
  { label: 'Infertility',       slug: 'infertility',        icon: Heart,         iconColor: '#BE185D', bg: 'from-pink-50 to-fuchsia-50',   desc: 'Fertility & reproductive health' },
  { label: 'STI / STD',         slug: 'sti',                icon: Shield,        iconColor: '#4338CA', bg: 'from-indigo-50 to-blue-100',   desc: 'Sexual health screening panel' },
  { label: "Men's Health",      slug: 'mens-health',        icon: Activity,      iconColor: '#1E40AF', bg: 'from-blue-50 to-indigo-100',   desc: 'Prostate & vitality check' },
  { label: 'Child Health',      slug: 'child-health',       icon: Baby,          iconColor: '#F59E0B', bg: 'from-yellow-50 to-orange-100', desc: 'Pediatric growth & wellness' },
  { label: 'Lipid Profile',     slug: 'lipid-profile',      icon: Heart,         iconColor: '#E11D48', bg: 'from-red-50 to-pink-50',       desc: 'Cholesterol & cardiac risk' },
  { label: 'Blood Sugar',       slug: 'blood-sugar',        icon: Droplets,      iconColor: '#0EA5E9', bg: 'from-blue-50 to-cyan-100',     desc: 'Glucose & insulin monitoring' },
  { label: 'Immunity',          slug: 'immunity',           icon: Shield,        iconColor: '#0F766E', bg: 'from-teal-50 to-emerald-100',  desc: 'Immune system strength check' },
  { label: 'Nutrition',         slug: 'nutrition',          icon: Zap,           iconColor: '#0D9488', bg: 'from-teal-50 to-cyan-50',      desc: 'Mineral & nutritional balance' },
  { label: 'Imaging & X-Ray',   slug: 'imaging',            icon: Activity,      iconColor: '#4F46E5', bg: 'from-indigo-50 to-sky-50',     desc: 'Radiology & imaging services' },
  { label: 'Joint & Arthritis', slug: 'joint',              icon: Bone,          iconColor: '#57534E', bg: 'from-stone-50 to-gray-50',     desc: 'Rheumatoid & joint health' },
  { label: 'Skin',              slug: 'dermatology',        icon: Star,          iconColor: '#EA580C', bg: 'from-orange-50 to-amber-50',   desc: 'Biotin & dermis vitality' },
  { label: 'Stress & Cortisol', slug: 'hormones',           icon: Brain,         iconColor: '#6D28D9', bg: 'from-violet-50 to-purple-50',  desc: 'Energy & stress management' },
];

export const WOMEN_CARE = [
  { label: 'PCOD Screening',    slug: 'hormones',           icon: FlaskConical,  iconColor: '#A21CAF', bg: 'from-fuchsia-50 to-purple-50', desc: 'Hormonal balance panel' },
  { label: 'Blood Studies',     slug: 'cbc',                icon: Activity,      iconColor: '#B91C1C', bg: 'from-red-50 to-orange-50',     desc: 'Complete blood count' },
  { label: 'Pregnancy',         slug: 'pregnancy',          icon: Baby,          iconColor: '#BE185D', bg: 'from-pink-100 to-rose-100',   desc: 'Safe motherhood screen' },
  { label: 'Iron Studies',      slug: 'iron-deficiency',    icon: Activity,      iconColor: '#991B1B', bg: 'from-red-50 to-rose-100',      desc: 'Anemia & vitality check' },
  { label: 'Vitamin Panel',     slug: 'vitamin',            icon: Zap,           iconColor: '#0891B2', bg: 'from-teal-50 to-cyan-100',     desc: 'D3, B12 & bone strength' },
  { label: 'Thyroid',           slug: 'thyroid',            icon: Brain,         iconColor: '#7C3AED', bg: 'from-purple-50 to-violet-100', desc: 'Metabolism & TSH scan' },
  { label: 'Bone Health',       slug: 'bone-health',        icon: Bone,          iconColor: '#65A30D', bg: 'from-lime-50 to-green-100',    desc: 'Calcium & density panel' },
  { label: 'Hormones',          slug: 'hormones',           icon: FlaskConical,  iconColor: '#A21CAF', bg: 'from-fuchsia-50 to-indigo-50', desc: 'Full endocrine profile' },
  { label: 'Fertility',         slug: 'infertility',        icon: Heart,         iconColor: '#BE185D', bg: 'from-pink-50 to-fuchsia-50',   desc: 'Reproductive health screen' },
  { label: 'STI Screening',     slug: 'sti',                icon: Shield,        iconColor: '#4338CA', bg: 'from-indigo-50 to-blue-100',   desc: 'Sexual wellness check' },
  { label: 'Immunity',          slug: 'immunity',           icon: Shield,        iconColor: '#0F766E', bg: 'from-teal-50 to-emerald-100',  desc: 'Overall health resistance' },
  { label: "Women's Wellness",  slug: 'womens-health',      icon: Star,          iconColor: '#DB2777', bg: 'from-pink-50 to-rose-100',     desc: 'Annual health checkup' },
];
